### ISSUE TITLE
EULA filelist incomplete

### ISSUE THREAD

**Issue by generateui** [Reactive-Extensions/Rx.NET#105]
[The Reactive Extensions EULA](https://msdn.microsoft.com/en-us/hh295787) has a link to the files included to be distributed in object code form. This [list](https://msdn.microsoft.com/en-us/hh881823.aspx) is currently:

* System.Reactive.dll
* System.Reactive.Providers.dll
* System.Reactive.Windows.Forms.dll
* System.Reactive.Windows.Threading.dll

However, the nuget packages

* Rx-Core.2.2.5
* Rx-Interfaces.2.2.5
* Rx-Linq.2.2.5
* Rx-PlatformServices.2.2.5
* Rx-Xaml.2.2.5

all refer to this Reactive Extensions Eula. These packages build to different files.

This issue prevents us from including these libraries into our enterprise software product. We are an ISV.

**Comment by onovotny** [comment]
Does the [license.txt](https://github.com/Reactive-Extensions/Rx.NET/blob/master/Rx.NET/Source/license.txt) in the repo address this? All of the code is released under Apache 2.0.

**Comment by onovotny** [comment]
The packages for 3.0 will be updated to point to the Apache license here: https://github.com/Reactive-Extensions/Rx.NET/blob/master/LICENSE 

No further EULA should be required.
