### ISSUE TITLE
calling .OnNext on any thread

### ISSUE THREAD

**Issue by reader-man** [Reactive-Extensions/Rx.NET#109]
Hi, 
can we call <b>.OnNext</B> on any thread, with out any problems, and if we can't, is it possible to done in your implementation of Rx.

Thanks on this powerful project.

**Comment by Dorus** [comment]
Assuming you created your Observable using Observable.Create() or one of the other factory methods (or worse case, a Subject): Yes, as per RX design guidelines, all calls to .OnNext() will be synchronized by the factory methods. Only when you implement your own Observable, you need to do this locking yourself (or call .Synchronize()).

**Comment by reader-man** [comment]
Thanks for your informative answer.
