### ISSUE TITLE
Ix-Async NuGet package framework assemblies are wrong

### ISSUE THREAD

**Issue by bricelam** [Reactive-Extensions/Rx.NET#114]
The Ix-Async package has the following structure.

* Ix-Async
  * lib
    * net40
    * net45
    * portable-\<targets>

But the nuspec has these framework assemblies.

```XML
<frameworkAssemblies>
  <frameworkAssembly assemblyName="System" targetFramework="" />
  <frameworkAssembly assemblyName="System.Core" targetFramework="" />
</frameworkAssemblies>
```

Because the `targetFramework` attribute is empty, it tries to add references to `System` and `System.Core` on Universal Windows Apps. To prevent this, the elements should look something like this.

```XML
<frameworkAssembly assemblyName="System.Core" targetFramework=".NETFramework4.0" />
```

/cc @rowanmiller @divega

**Comment by BrainCrumbz** [comment]
[cleanup] PR has been merged time ago. Maybe this can be closed now?

**Comment by onovotny** [comment]
this is fixed in `master`
