### ISSUE TITLE
Add SwitchFirst()

### ISSUE THREAD

**Issue by paulpdaniels** [Reactive-Extensions/Rx.NET#118]
RxJS has a very useful operator called [`switchFirst()`](https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/core/operators/switchfirst.md) which unlike `Switch`, holds onto the first `Observable` it receives and holds its subscription until it completes before subscribing to a new one. All intermediate `Observables` are dropped on the floor. Is there any interest having this ported to Rx.NET? Or is there another way for this that I am not seeing?

**Comment by Dorus** [comment]
`Amb()` holds onto the first observable it receives, but does not subscribe to subsequent observables.
`Switch()` does subscribes to subsequent Observables but doesn't wait for them to complete.

I suppose you can make a extension method like this:
```C#
        public static IObservable<TSource> SwitchFirst<TSource>(this IObservable<IObservable<TSource>> source) {
            return Observable.Create<TSource>(o => {
                bool free = true;
                return source.Where(_ => free).Select(el => el.Do(_ => free = false).Finally(() => free = true)).Switch().Subscribe(o);
            }
            );
        }
```
I agree that having this operator natively would be really nice.

**Comment by Dorus** [comment]
There is also this slightly more threadsafe version (Shouldn't be required if the preceding source follows Rx contract i think, but it wont hurt).
```C#
        public static IObservable<TSource> SwitchFirstSafe2<TSource>(this IObservable<IObservable<TSource>> source) {
            return Observable.Create<TSource>(o => {
                int free = 1;
                return source.Where(_ =>
                    Interlocked.CompareExchange(ref free, 0, 1) == 1
                ).Select(el => el.Finally(() => free = 1)).Switch().Subscribe(o);
            }
            );
        }
```

**Comment by paulpdaniels** [comment]
I realize I have let this one sit for a while. My use case for this though was that I was creating a rate limited client API that needs to hit a backend when the user refreshes, but I don't just want to slam the server every time the user presses the button. It should wait until the previous request returns before allowing new ones to go out.

**Comment by Dorus** [comment]
The scenario you describe now is usually solved with Sample or Throttle. Both do require that you either have a known timeout value when the server is ready, or your subscription is blocking so Sample know not to yield the next value just yet.

**Comment by paulpdaniels** [comment]
Yes, I am using `Sample` right now but it is not a terribly clean solution. I suppose I may just end up porting the RxJS version. I'll close this for now since this issue hasn't really garnered any support.
