### ISSUE TITLE
`Observable.Timer(TimeStamp, TimeStamp, IScheduler)` invoked on specified scheduler only first time

### ISSUE THREAD

**Issue by mstyura** [Reactive-Extensions/Rx.NET#127]
It looks like issue with [documentation](https://msdn.microsoft.com/en-us/library/hh229652(v=vs.103).aspx) or with [implementation](https://github.com/Reactive-Extensions/Rx.NET/blob/master/Rx.NET/Source/System.Reactive.Linq/Reactive/Linq/Observable/Timer.cs#L190): when you use `Observable.Timer(TimeStamp, TimeStamp, IScheduler)`  to performs some periodic task on specified scheduler (UI is particular case) only first run is performed on specified scheduler, all subsequent runs are performed on wrong scheduler which result in cross thread access in subscribe method.

**Comment by glopesdev** [comment]
Can you provide some simple example code that reproduces this issue?

**Comment by mstyura** [comment]
@glopesdev sorry, fault was on my side.
