### ISSUE TITLE
InvalidOperationException in Buffer when accessing from multiple threads

### ISSUE THREAD

**Issue by TMaster** [Reactive-Extensions/Rx.NET#129]
Hi,

I tried to use the Buffer extension method in my application.

I need to access the observable from multiple threads, and when I do so, I get an InvalidOperationException with the description of "Queue Empty"

I saw that you use Queue and try to Dequeue an item in the OnNext method which I think cause the exception.

Right now I overcome the problem by using Synchronize() before the Buffer().

Is there anyway to handle this instead of using Synchronize()

Thanks

**Comment by Dorus** [comment]
Yes, you need to follow the Rx contract. While it is allowed for different messages to arrive at different execution contexts at the same time, you still need to call them in a serialized fashion. See also Rx design guidelines 4.2 and 5.8. All Rx operators assume you do so (not all of them crash equally horrible if you don't, but trouble is assured).

Simply said, either add your own locking mechanism to make these calls serialized, or call `Synchronize()` as you already discovered.
