### ISSUE TITLE
MissingManifestResourceExceptions on Release builds on Windows Phone 8.1 store apps

### ISSUE THREAD

**Issue by idg10** [Reactive-Extensions/Rx.NET#13]
If you build a Windows Phone 8.1 store app that uses Rx, and you run the Release build on an actual device (not the emulator), you will encounter `MissingManifestResourceExceptions` in scenarios in which Rx should be calling `OnError` on its subscribers.

This does not happen in Debug builds. And it only happens in Release builds if you run the code on a real phone - the problem does not occur on the phone emulator.

To repro this, I just created a new 8.1 Phone Store App in Visual Studio 2013 (Update 2), and then added a NuGet reference to Rx-Main (2.2.4). Then in the `MainPage.xaml.cs` codebehind, I added this to the constructor:
```c#
    var src = new Subject<int>();
    IObservable<int> shouldError = src.FirstAsync();
    shouldError.Subscribe(
        i => Debug.WriteLine(i),
        x => Debug.WriteLine("Error: " + x));
    src.OnCompleted();
```
Since I'm using `FirstAsync` on a source that completes without producing items, the expected outcome here is that my error handler should run. And if I run the Debug build (on either the emulator or a real phone) that's exactly what happens - I see this in my Debug output in VS: 

`Error: System.InvalidOperationException: Sequence contains no elements.`

 If I run the Release build on the emulator, there's no debug output of course, because the `Debug.WriteLine` gets compiled out, but it runs without error. 

 But if I run the Release build on a real device (a Nokia Lumia 620) the app crashes - an unhandled `MissingManifestResourceException` emerges from that call to `OnCompleted`. Here's the detail:
```
System.Resources.MissingManifestResourceException occurred
  _HResult=-2146233038
  _message=[MissingManifestResource_NoPRIresources]
Arguments: 
Debugging resource strings are unavailable. Often the key and arguments provide sufficient information to diagnose the problem. See http://go.microsoft.com/fwlink/?linkid=106663&Version=4.0.30227.0&File=mscorlib.dll&Key=MissingManifestResource_NoPRIresources
  HResult=-2146233038
  IsTransient=false
  Message=[MissingManifestResource_NoPRIresources]
Arguments: 
Debugging resource strings are unavailable. Often the key and arguments provide sufficient information to diagnose the problem. See http://go.microsoft.com/fwlink/?linkid=106663&Version=4.0.30227.0&File=mscorlib.dll&Key=MissingManifestResource_NoPRIresources
  Source=mscorlib
  StackTrace:
       at System.Resources.ResourceManager.GetString(String name, CultureInfo culture)
  InnerException:
```
Here's the stack trace:
```
mscorlib.ni.dll!System.Resources.ResourceManager.GetString(string name, System.Globalization.CultureInfo culture)
System.Reactive.Linq.ni.DLL!System.Reactive.Strings_Linq.NO_ELEMENTS.get()
System.Reactive.Linq.ni.DLL!System.Reactive.Linq.ObservableImpl.FirstAsync<int>._.OnCompleted()
System.Reactive.Linq.ni.DLL!System.Reactive.Subjects.Subject<int>.OnCompleted()
```
As far as I can tell, Rx is attempting to look up a localizable version of that "Sequence contains no elements." error message in order to construct the `InvalidOperationException` before passing that onto the subscriber's `OnError`. But because the resource lookup failed, the subscriber never sees anything, and instead the code calling `Subject.OnCompleted` receives this resource lookup exception.

**Comment by bartdesmet** [comment]
It seems like http://stackoverflow.com/questions/26140155/missingmanifestresourceexception-on-windows-phone-8-1-with-resx-resources/27029175#27029175 describes this problem and a possible solution. The problem seems to be broader than Rx alone, affecting all Portable Class Libraries used in such an application. Resolving as external.

**Comment by idg10** [comment]
The solution described at http://blogs.msdn.com/b/philliphoff/archive/2014/11/19/missingmanifestresourceexception-when-using-portable-class-libraries-in-winrt.aspx works, but it does rely on a) knowing the name of the class Rx is using to load its resource and b) reflecting against its fields and modifying one of them at runtime!

So I feel a bit queasy using this. But for the benefit of others coming across this issue, here's what you do. Before using rx you'll need to execute this code:

    WindowsRuntimeResourceManager.InjectIntoResxGeneratedApplicationResourcesClass(
        typeof(Observable).GetTypeInfo().Assembly.GetType("System.Reactive.Strings_Linq"));

This relies on the class from that blog entry which, for convenience, I've copied here:

    public class WindowsRuntimeResourceManager : ResourceManager
    {

        private readonly ResourceLoader resourceLoader;

        private WindowsRuntimeResourceManager(string baseName, Assembly assembly)
            : base(baseName, assembly)
        {
            this.resourceLoader = ResourceLoader.GetForViewIndependentUse(baseName);
        }

        public static void InjectIntoResxGeneratedApplicationResourcesClass(Type resxGeneratedApplicationResourcesClass)
        {
            resxGeneratedApplicationResourcesClass.GetRuntimeFields()
              .First(m => m.Name == "resourceMan")
              .SetValue(null, new WindowsRuntimeResourceManager(resxGeneratedApplicationResourcesClass.FullName, resxGeneratedApplicationResourcesClass.GetTypeInfo().Assembly));
        }

        public override string GetString(string name, CultureInfo culture)
        {
            return this.resourceLoader.GetString(name);
        }
    }
