### ISSUE TITLE
Rx.NET reactive or what ever?

### ISSUE THREAD

**Issue by mydiscogr** [Reactive-Extensions/Rx.NET#138]
Hi I'm bit confused, 
because I have find this Rx.NET,  I think is official one from Microsoft

but this is the same?
https://www.nuget.org/packages/Rx-Main/2.3.0-beta2... it's the same as this?

which is the latest release? I like reactive and I'd like to learn more but why 2 libs?

and where is the nuget package...?

thanks

**Comment by mydiscogr** [comment]
nobody can answer? I know is nubie question maybe...

**Comment by flagbug** [comment]
Yes, https://www.nuget.org/packages/Rx-Main is the offical Reactive Extensions release.

2.2.5 is the latest stable version, 2.3.0-beta2 is the latest prerelease version

**Comment by mydiscogr** [comment]
ok thanks :+1:

**Comment by GeertVL** [comment]
There is no active development anymore? 6 months ago latest commit. 
What for future versions? Is IObservable<T> and IObserver<T> the only thing that is left?

**Comment by shiftkey** [comment]
@GeertVL I can't speak for the team, but we're looking to give this project a bit of a reboot in the coming weeks. Once we have something to announce, you'll hear about it!

**Comment by LeeCampbell** [comment]
Can we close this issue.

**Comment by grahamehorner** [comment]
@shiftkey @bartdesmet would love to know what is happening with regard the IRP work demoed almost a year ago?  @LeeCampbell I'd be ok with closing the issue but opening a general project update needed; reference this issue given @shiftkey comment above ;) just my 2p worth

**Comment by GeertVL** [comment]
@shiftkey @bartdesmet any announcement yet that I missed? or any roadmap publishment? Can we help? You could close this issue if we know where this project is going.

**Comment by onovotny** [comment]
Please see the announcement here: http://www.dotnetfoundation.org/blog/rx-net-welcome

**Comment by GeertVL** [comment]
Thank you. Great news!
