### ISSUE TITLE
ExecutionContext does not flow consistently

### ISSUE THREAD

**Issue by bman654** [Reactive-Extensions/Rx.NET#14]
See this Rx [discussion thread](http://social.msdn.microsoft.com/Forums/en-US/9b96c83a-13ec-4943-80ca-df01f94df683/executioncontext-does-not-flow-consistently-through-observables?forum=rx) for the full details.

But generally speaking, observables ExecutionContext from the notification source down to the observer.  Observer callbacks fire within the notification source's execution context.

For cold observables, the 2 contexts are usually the same.  But for hot observables, the 2 contexts can be different and it becomes unpredictable to know what context your callbacks will run in.  And this flow direction tends to be counter-intuitive and doesn't really align with the way Tasks flow the execution context.

Should this behavior be changed?

**Comment by bartdesmet** [comment]
We've discussed this at length back in the day when we were designing Rx. Lee's explanation on the free threaded nature is spot on. In Rx, one has to explicitly parameterize concurrency using mechanisms such as ObserveOn.
