### ISSUE TITLE
ObserverBase isStopped thread safety question

### ISSUE THREAD

**Issue by tmds** [Reactive-Extensions/Rx.NET#143]
I was looking at the code of ObserverBase and I found it strange that OnNext and Dispose don't do anything special to ensure thread safety of isStopped.

If thread A calls Dispose, how is it ensured that thread B which calls OnNext sees this change of isStopped?

**Comment by RxDave** [comment]
That's right, you have to synchronize calls to ```ObserverBase<T>```, observers passed to ```ObservableBase<T>```, calls to ```Subject<T>```, and perhaps all subjects defined by Rx, yourself.

It wasn't always like this with ```Subject<T>```, but as a performance optimization in the initial release (or was it 2.0?) the Rx team decided that in most cases synchronization wasn't needed, so it wasn't worth the overhead to ensure that notifications are serialized; however, Rx operators still require that notifications are serialized (§§4.2, 6.7 [Rx Design Guidelines](https://github.com/Reactive-Extensions/Rx.NET/blob/master/Rx.NET/Documentation/Rx%20Design%20Guidelines.pdf)).

The easiest way is to use the [Synchronize](https://msdn.microsoft.com/en-us/library/system.reactive.linq.observable.synchronize(v=vs.103).aspx) method for ```IObservable<T>```, the [Synchronize](https://msdn.microsoft.com/en-us/library/system.reactive.observer.synchronize(v=vs.103).aspx) method for ```IObserver<T>``` or the [Synchronize](https://msdn.microsoft.com/en-us/library/system.reactive.subjects.subject.synchronize(v=vs.103).aspx) method for ```ISubject<T>```.

**Comment by RxDave** [comment]
_I deleted my previous answer, which was factual, but I don't think that it actually answered your question._

The Rx team has always stated that unsubscription is "best effort".

There's an inherent race condition between cancellation and computation that's ultimately irrelevant here, especially given that the state of cancellation isn't exposed publicly by ```ObserverBase<T>```

Take your example: Thread *A* calls ```Dispose``` just before thread *B* calls ```OnNext```. 
So what is your expectation here? Should thread *B* block while *A* is disposing the subscription? It probably doesn't matter if *B* notifies successfully sometime after *A* has successfully cancelled the subscription, given that *B* cannot know whether the observer is actually disposed or not, and perhaps that avoiding this race condition doesn't justify the cost of a lock, or even any lighter-weight synchronization mechanism.

**Comment by RxDave** [comment]
Thinking about it some more, there is perhaps a scenario on certain multi-processor architectures, related to caching of ```isStopped```, that could theoretically cause a sequence of serialized calls to ```OnNext``` such as A B C to be observed as A C, whereby the thread that pushed B saw ```isStopped``` as 1 while the other notifications threads' saw 0. Seems very unlikely, but plausible (though I don't think it applies to Intel?)

**Comment by tmds** [comment]
Yes, that is indeed what I am wondering about.
I would have expected to see a Volatile.Read and a Volatile.Write on isStopped to ensure there is a MemoryBarrier.

**Comment by bartdesmet** [comment]
Seems like an omission; it'd need volatile treatment.

**Comment by onovotny** [comment]
@bartdesmet can you please review #220 for the fix?
