### ISSUE TITLE
Observable.SelectWhere method

### ISSUE THREAD

**Issue by NN---** [Reactive-Extensions/Rx.NET#147]
Sometimes I need do map values but not pass it.
Currently I use Select + Where:

```cs
Observable.Range(10).Select(x => x + 1).Where(x => x % 2 == 0)
```

The drawback of this solution is that Select always produces values even when I don't need them after that.
I would like to add a new method SelectWhere which receives both the projection and the filter.
It will be more semantically correct and will be more efficient:

```cs
Observable.Range(10).SelectWhere(x => x + 1, x => x % 2 == 0)
```

In general it is merge of Where.cs with Select.cs files.

Same can be done for IEnumerable interface.

What do you think ?

**Comment by tamirdresher** [comment]
I'm not sure i see the use of it. 
you are still going to invoke the selector function and create the new value, so what did you save? just the call to the OnNext?

**Comment by NN---** [comment]
Exactly.
It saves call for OnNext.
You also don't need to make dummy value for the Where clause.
And semantically it is easier to understand .

**Comment by paulpdaniels** [comment]
You'd still have to invoke the select and Where clause for every value. Plus now you'd have an operator that is decidedly less flexible. Compared to other tasks the overhead for one more method call is minuscule.

**Comment by NN---** [comment]
I see what you are saying.
Guess you are right.
If I find something better I'll reopen it again.
Thanks.
