### ISSUE TITLE
CoreCLR

### ISSUE THREAD

**Issue by grahamehorner** [Reactive-Extensions/Rx.NET#148]
Please consider creating an implementation that supports CoreCLR target platforms.

**Comment by khellang** [comment]
I'd :heart: this :+1:

**Comment by onovotny** [comment]
Yes.

**Comment by khellang** [comment]
@onovotny You could try to build https://github.com/Reactive-Extensions/Rx.NET/pull/151 if you want to test.

**Comment by onovotny** [comment]
Any word on this from the Rx team? @bartdesmet? CoreCLR support is super-important.

**Comment by niemyjski** [comment]
I need this as well

**Comment by BlasVilla** [comment]
Any update on this? We are migrating to .NET Core and we need a port, event if we have to do some of the work ourselves

**Comment by onovotny** [comment]
There is an effort in progress here....hopefully news to be shared soon? /cc @shiftkey

**Comment by khellang** [comment]
@BlasVilla I think you can use the portable version on core already, like EF does with Ix-Async [here](https://github.com/aspnet/EntityFramework/blob/dev/src/Microsoft.EntityFrameworkCore/project.json#L13). The trick is to [import `portable-net452+win81`](https://github.com/aspnet/EntityFramework/blob/dev/src/Microsoft.EntityFrameworkCore/project.json#L31) :smile:

**Comment by shiftkey** [comment]
@onovotny @BlasVilla Yep, hopefully we'll have some news to share in the next couple of weeks.

**Comment by danbarua** [comment]
Any news?

**Comment by BlasVilla** [comment]
We are using Rx.NET with no problems. Thanks for the tip @khellang!
Now we are looking into running Docker containers and we end up with some limitations because we cannot use Linux base images. Any news on Rx.NET support for dnxcore50?

**Comment by onovotny** [comment]
We have this working with CLI on pre-RC2 bits in a private repo. There are a few outstanding issues to solve first though.

**Comment by grahamehorner** [comment]
@onovotny happy to help out and try stuff if your able the share private repo; I hear that next week is going to be a week we all hear about the timeline of  dotnet cli asp.net core rc2 tooling etc. do you know will Rx.NET follow that timeline ? or be included to coincide with the release?

**Comment by shiftkey** [comment]
@grahamehorner lots of things are beyond our control right now, but hopefully once the new tooling drops we can pick up things with the team (the team does the codesigning and publishing of releases in the end) and co-ordinate on how to proceed...

**Comment by grahamehorner** [comment]
@shiftkey totally understand; some BIG changes happening for .NET in the cross-platform space :D

**Comment by onovotny** [comment]
Use this feed: `https://www.myget.org/F/rxnet/api/v3/index.json`

I pushed bits
use that feed
all tests pass
don't spread too wide yet
(Ix.NET is there too)
You'll have to rename your packages as well -- System.Reactive is the one you want to replace Rx-Main

This is an early beta and needs validation.

**Comment by natemcmaster** [comment]
@onovotny any particular reason you chose to depend on NETStandard.Library instead of individual packages from the BCL?

```xml
      <group targetFramework=".NETStandard1.0">
        <dependency id="NETStandard.Library" version="1.5.0-rc2-24027" />
      </group>
```

https://www.myget.org/feed/rxnet/package/nuget/System.Interactive.Async

**Comment by onovotny** [comment]
Yes, laziness for now to get the packages out quicker. I need to figure out the best way of running the nuspec generator tool across multiple outputs because support netstandard 1.0 and 1.3 in most cases. 

The dependency lists will get cleaned up.

**Comment by natemcmaster** [comment]
:+1: glad this work is happening. Entity Framework uses Ix-Async, and we're also hoping to get a .NET Standard version. https://github.com/aspnet/EntityFramework/issues/5176

**Comment by danielcrenna** [comment]
@onovotny I'm not sure if this simply a permissions issue but I am able to resolve the .NET Standard version of System.Reactive.Interfaces, but the System.Reactive.Core project can't resolve System.Reactive.Interfaces itself, resulting in a broken/failed package restore, even though all the parts are available on the feed.

**Comment by onovotny** [comment]
@danielcrenna Good catch. I fat-fingered the dependency and it was missing an R in InteRfaces. I've pushed a later version that fixes this (00364).

BTW, for the most part, the only package you should need to reference is `System.Reactive`. It's what was `Rx-Main` and pulls in the other packages for you.

**Comment by danielcrenna** [comment]
@onovotny Thanks! In my case I was porting over a library that only required `Rx-Core` to begin with.

**Comment by danielcrenna** [comment]
@onovotny It kind of maybe sort of looks like the typo is still there, and whatnot, at least in the consuming packages' .NUSPECs
![image](https://cloud.githubusercontent.com/assets/129610/15343060/c25cb4b6-1c67-11e6-97c6-6ee121bb52eb.png)

**Comment by onovotny** [comment]
sigh, sorry again, it was in two places, and I only fixed one. New one is building now, will be up in about 20 min.

**Comment by onovotny** [comment]
Alright, should be good this time -- 00365 is now on MyGet with that fix.

**Comment by danielcrenna** [comment]
@onovotny Mmhmm, I have it now. Thanks for your help!

**Comment by Luke47** [comment]
I get the following error, when I try to install `System.Reactive`, am I missing something?

`Could not install package 'Microsoft.NETCore.Runtime.Native 1.0.2-rc2-24027'. You are trying to install this package into a project that targets 'WindowsPhoneApp,Version=v8.1', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.`

**Comment by onovotny** [comment]
What version of VS and what version of NuGet? The packaging may need to be tweaked for some platforms.

**Comment by Luke47** [comment]
I'm using

- MS Visual Studio Enterprise 2015
Version 14.0.25123.00 Update 2
- NuGet Package Manager 3.4.3

**Comment by onovotny** [comment]
Tracking that one here: https://github.com/dotnet/corefx/issues/8649

**Comment by onovotny** [comment]
@Luke47: Looks like an RC2 issue that has been fixed for RTM: https://github.com/dotnet/corefx/issues/8649#issuecomment-220078632

**Comment by SuperJMN** [comment]
+1

**Comment by danielcrenna** [comment]
I haven't had any issues with the beta bits to date on RC2.

**Comment by onovotny** [comment]
Completed, shipping on 6/27
