### ISSUE TITLE
async/await IObservable<TSource>.GetAwaiter() Extension method 'too' prominently placed?

### ISSUE THREAD

**Issue by jbattermann** [Reactive-Extensions/Rx.NET#156]
I think it is really quite nice that one can await IObservables but I wasn't quite happy with AsyncSubject<T>'s implementation of 'only' returning the last received value prior to completion and returning that one to the awaitee.. erm.. awaiting caller.

Anyway, I went ahead and implemented my own that basically buffers received elements and returns them all on completion back to the awaiting caller, but now I have a problem:

The extension method RX.Net provides to make await possible is right inside the static [System.Reactive.Linq.Observable](https://github.com/Reactive-Extensions/Rx.NET/tree/master/Rx.NET/Source/System.Reactive.Linq/Reactive/Linq) class, among aaaaall the other good RX extension methods.

Now because [```public static AsyncSubject<TSource> GetAwaiter<TSource>(this IObservable<TSource> source)```](https://github.com/Reactive-Extensions/Rx.NET/blob/master/Rx.NET/Source/System.Reactive.Linq/Reactive/Linq/Observable.Awaiter.cs#L20) is in there too, it's *unnecessarily* difficult to discover and use a custom await/.GetAwaiter() implementation. One can either use or have a ```using System.Reactive.Linq;``` statement and therefore all ```await myObservable``` usages implicitely use the RX.net implementation but thereby also enforcing that usage of a custom await / GetAwaiter implementation must be something like ```await MyOwnObservableExtensions.GetAwaiter(myObservable);``` .. which is a bit counterintuitive. Or I break up implementation into separate partial classes / files etc.

If I specify my own / my extension methods class' namespace, I similarly must call all RX.net extension methods like (non extension) methods.

Specifying both namespaces obviously yields a compiler error (amibguous call / duplicate signatures etc).

My question / suggestion / wish basically is whether async/await support for IObservable<T>s and therefore the GetAwaiter extension method could be moved to its own, i.e. *Async namespace rather than "blocking" custom implementations by being too prominently placed right in the middle of the 'core' IObservable<T> extension methods.

Writing custom await / GetAwaiter() implementations is rather a niche use-case but maybe it's worth considering for sometimes down the road..

Cheers,
-Jörg

**Comment by RxDave** [comment]
Have you tried this?

await xs.ToList();

**Comment by jbattermann** [comment]
Nope -.- but of course that works.. had a sort of facepalm moment the moment I read it - But thanks Dave!

It doesn't really 'solve' my general inquiry regarding custom awaiter handling / overlap but *my* need for a custom awaiter is gone again.
