### ISSUE TITLE
Windows phone 8.1, not works

### ISSUE THREAD

**Issue by mydiscogr** [Reactive-Extensions/Rx.NET#157]
Hi, I've used nuget version Reactive extension (https://www.nuget.org/packages/Rx-Core/2.2.5), not sure if the same of this or not, bytheway for windows phone 8.1 and not works, 
the message is can't find  "... corerx.dll into portable/ etc." seems that portable library aren't compiled for universal app/windows phone 8.1.

So I download this repository and try to compile, but no luck, too many errors, any idea...??

**Comment by Luke47** [comment]
Did you solve this already? I have the same issue.

**Comment by onovotny** [comment]
#148 will work on Wpa81

**Comment by onovotny** [comment]
Fixed in 3.0, shipping on the 27th
