### ISSUE TITLE
Internal factory methods in Ix-Async 

### ISSUE THREAD

**Issue by Yshayy** [Reactive-Extensions/Rx.NET#159]
Hi,
I'm trying to write a method that continuously pull data from storage based on task api that use paging with continuation token.
I implemented it with Rx Observable, but I prefer to move the control to the consumer.
The methods I saw that felt suitable for the creation of the AsyncEnumbrable were internal:
```csharp
static IAsyncEnumerator<T> Create<T>(Func<CancellationToken, Task<bool>> moveNext, Func<T> current, Action dispose)

static IAsyncEnumerable<T> Create<T>(Func<IAsyncEnumerator<T>> getEnumerator)
```
Is there any other recommended way to do it? (Like implementing the interfaces with classes)
What's the reason these methods are internal?

**Comment by bartdesmet** [comment]
These could be made public. There's no fundamental reason they were kept internal; we just tried to keep API surface minimal back in the day.

**Comment by Yshayy** [comment]
Sounds great, we currently solve it by just copying these methods to our project source code, but it's not ideal.
I can create a PR for that.

**Comment by slang25** [comment]
Hey, just found this issue after doing the same thing (copying the internals into my project). I have come across another OS project that has done a similar thing:
https://github.com/Adamantworks/Amazon.DynamoDB/blob/master/DynamoDB/Internal/AsyncEnumerableEx.cs
This seems such a necessary API to include. I agreed with @Yshayy, those 2 overloads seem the best candidates to make public.
