### ISSUE TITLE
MostRecent does not work with Observable.Return

### ISSUE THREAD

**Issue by heebj** [Reactive-Extensions/Rx.NET#161]
When MostRecent is used on an Observable created with the Return factory method, an InvalidOperationException occurs with the message "Sequence contains no elements".

Is this expected behaviour or is it a bug?

**Comment by heebj** [comment]
If I use a BehaviorSubject with initial value x instead of Observable.Returns(x) it works as expected...

**Comment by LeeCampbell** [comment]
Remember that `Observable.Return(42)` is actually the following sequence 'OnNext(42);OnCompleted();'

If you use a BehaviorSubject and don't complete it then you have effectively a different sequence.
i.e. 
`Observable.Return(42)` is more like 

	var bs = new BehaviorSubject<int>(42);
	bs.OnCompleted();

When you use the operator `MostRecent`, it will (AFAIK) try to _pull_ the most recent value from the sequence when you `MoveNext` on the `IEnumerable` that it returns. When using the `Observable.Return` operator, it will synchronously yield the value and then the completion. So when you attempt to pull the _most recent value_ it will see that the sequence is already completed. Thus there are now values.

I assume the exception you are seeing is actually from another LINQ operator like `.Sum` or `.First()`

**Comment by bartdesmet** [comment]
@LeeCampbell's explanation is right. You'd need to apply MostRecent to Return(42).Concat(Never()) or a non-terminated BehaviorSubject in order to avoid the OnCompleted to terminate the enumerable sequence.
