### ISSUE TITLE
Please Consider Updating CodePlex Site to Point to This Repo

### ISSUE THREAD

**Issue by Mike-EEE** [Reactive-Extensions/Rx.NET#162]
I have been reading a lot of chatter these past few years regarding Rx and I am happy to say that I am now checking it out.  In the process of doing so, I was led to the codeplex site from MSDN.  This site appears to be now defunct (even though it says it is actively developed).

Does someone on this repo have access/authority to update this site to reflect the true nature of its state?  I have spent some time in confusion (and almost ended up posting a question to StackOverflow haha) over this.  

It would be great to help other slowpokes like me onramping to this tech and show them the way here quicker.

FWIW, the discussion on the CodePlex site regarding this issue:
https://rx.codeplex.com/discussions/648420

**Comment by Michael-DST** [comment]
FWIW, the MSDN site I referenced:
https://msdn.microsoft.com/en-us/data/gg577609

As such, it wasn't this site that led me to the CodePlex site (busy morning).  There are other [older blog posts](http://blogs.interknowlogy.com/2013/01/31/mixing-tpl-dataflow-with-reactive-extensions/) that are pointing to the CodePlex site that will lead others like me to the undesired state of confusion.

**Comment by damianh** [comment]
https://twitter.com/randompunter/status/664820330364583936

Not sure they can close it but they could, at the very least, update the home page to point to github. See https://xunit.codeplex.com/ as example.

**Comment by Michael-DST** [comment]
excellent @damianh and thank you for that tweet. :)  I have updated the title to reflect this suggestion and actually the original intent of what I was after.  It was a busy morning, what can I say. :stuck_out_tongue:

**Comment by onovotny** [comment]
Fixing as part of #184

**Comment by damianh** [comment]
Looks like this project has some life back in it. Great!
