### ISSUE TITLE
Possible IX-Async cancellation bug 

### ISSUE THREAD

**Issue by anpete** [Reactive-Extensions/Rx.NET#166]
Consider the following:

```c#
var cts = new CancellationTokenSource();
var task = AsyncEnumerable.Repeat("Foo", 10).Where(s => true).ToList(cts.Token);

cts.Cancel();

var results = task.Result;

Assert.AreEqual(10, results.Count);
```

When executing this code multiple times in a loop, we can observe two different behaviors:

1) TaskCanceled exception is raised during the call to _.Result._
2) No exception is raised and the last assert fails. _results_ contains a single element.

The behavioral difference looks to be the result of a race between the Dispose call [here](https://github.com/Reactive-Extensions/Rx.NET/blob/master/Ix.NET/Source/System.Interactive.Async/AsyncEnumerable.Creation.cs#L45) and the MoveNext call [here](https://github.com/Reactive-Extensions/Rx.NET/blob/master/Ix.NET/Source/System.Interactive.Async/AsyncEnumerable.Creation.cs#L78).

@bartdesmet Can you please comment?

**Comment by onovotny** [comment]
This should be fixed in #237 as the base iterator was rewritten to prevent conditions.
