### ISSUE TITLE
Duplicate IObservable type

### ISSUE THREAD

**Issue by roschler** [Reactive-Extensions/Rx.NET#169]
When I try to reference the DLLs built by this project from the LinqToTwitter (Joe May) Portable Class Library that targets .NET framework 4.5, I get the following fatal error:

Error	1	The type 'System.IObservable<T>' exists in both 'c:\Visual Studio 2012\Projects\Windows Forms\Oleria\Rx.NET\Rx.NET\Source\bin\Debug35\System.Reactive.Interfaces.dll' and 'c:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETPortable\v4.5\Profile\Profile7\System.Runtime.dll'	C:\Visual Studio 2012\Projects\Windows Forms\Oleria\LinqToTwitterPcl\LinqToTwitter\TwitterExtensions.cs	31	34	LinqToTwitterPcl

How can I fix this?

**Comment by shiftkey** [comment]
@roschler you need to change the build configuration to one of the PCL-based targets as frameworks after v4.0 have this interface already available (.NET 3.5 doesn't, hence it being added in to the interfaces project)

One of these should work:

 - `DebugPL`
 - `ReleasePL`
 - `DebugPLLITE`
 - `ReleasePLLITE`

**Comment by bartdesmet** [comment]
Seems like @shiftkey has the right answer here. Did that work for you?

**Comment by marcosrocha85** [comment]
Sorry for revive this post, but I tried to use DebugPL on "Conditional compilation symbols" but didn't solved the problem. I having this message:

> Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0433	The type 'Observable' exists in both 'System.Reactive.Linq, Version=3.0.3000.0, Culture=neutral, PublicKeyToken=94bc3704cddfc263' and 'System.Reactive, Version=1.0.10621.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'	Financial	C:\Projects\TestReactiveX\ConnectWithMySQL.cs	27	Active

How can I deal with that?
