### ISSUE TITLE
Lose stack trace with the Stubs.Throw implementation

### ISSUE THREAD

**Issue by markmcdowell** [Reactive-Extensions/Rx.NET#17]
In the current implementation of `DefaultExceptionServices` the exception is thrown, this means a new stack trace is created and we only keep the actual message. e.g.
```csharp
internal class DefaultExceptionServices : IExceptionServices
{
        public void Rethrow(Exception exception)
        {
            throw exception;
        }
}
```

To keep the stack trace it would be better to wrap the exception. e.g. 
```csharp
internal class DefaultExceptionServices : IExceptionServices
{
        public void Rethrow(Exception exception)
        {
            throw new Exception(exception.Message, exception);
        }
}
```

**Comment by bartdesmet** [comment]
We need to keep the original exception type, so we can't change this behavior. For .NET 4.5 and beyond, it uses ExceptionDispatchInfo to preserve the stack trace.
