### ISSUE TITLE
Support .NET Platform Standard

### ISSUE THREAD

**Issue by andriysavin** [Reactive-Extensions/Rx.NET#174]
Need to add support for .NET Platform Standard for easier referencing from netstandard libraries. 
Here's is motivation for this: I tried to reference the Rx PCL package from a netstandard library with ["imports"](https://github.com/dotnet/corefx/blob/master/Documentation/architecture/net-platform-standard.md#portable-profiles)  trick usage, but I wasn't able to build that library - many errors arise when adding "imports", like LINQ becomes "invisible" to the compiler (**all that happens when targeting netstandard1.4 and lower**). And after all, this trick is more for third parties which don't hurry to adopt recent .Net trends; Rx, on the other hand, is Microsoft's child and should not hesitate to do that.

This seems to be relatively easy to do (at least for the first step), since there is a PCL version (Profile259) of Rx which is compatible with netstandard1.0. If I understand [this](https://github.com/dotnet/corefx/blob/master/Documentation/architecture/net-platform-standard.md#package-authoring) document correctly, those PCL binaries should just be copied to a netstandard1.0 directory when producing packages, and also dependencies should be specified.

**Comment by onovotny** [comment]
Dup of #148

**Comment by SuperJMN** [comment]
Support for .NET Standard profiles. Including 1.5!

**Comment by onovotny** [comment]
completed!
