### ISSUE TITLE
nuget package drop and positioning of this for transient fault handling

### ISSUE THREAD

**Issue by myusrn** [Reactive-Extensions/Rx.NET#176]
is there a nuget package for enabling use of rx.net in a csharp project environment?

is rx.net what one could consider the open source initiative replacement for transient fault handling functionality that the old patterns & practices block [ https://msdn.microsoft.com/en-us/library/hh675232.aspx ] covered?

**Comment by shiftkey** [comment]
> is there a nuget package for enabling use of rx.net in a csharp project environment?

https://www.nuget.org/packages/Rx-Main

> is rx.net what one could consider the open source initiative replacement for transient fault handling functionality ...

I'd look at something like `RetryWithBackoffStrategy` which you can add on top of Rx (link then links off to some source code): 

http://stackoverflow.com/questions/18978523/write-an-rx-retryafter-extension-method

**Comment by myusrn** [comment]
thanks for response and pointers to relevant info.

so does rx.net [ and .js ] provide retries when a transient fault arises but just not with any oob support for only retrying depending on the nature of the fault/exception and/or ability to wait an increasing amount of time between each retry vs retrying right away?

**Comment by shiftkey** [comment]
@myusrn no, not out of the box. But as the sample above shows, it's easy to build on top and I highly recommend trying it out to get familiar with Rx more...

**Comment by bartdesmet** [comment]
It seems the pointers to the NuGet package were the main missing link to get started. As @shiftkey points out, there's no built-in support for the transient fault handling, but it'd be easy to build on top of the primitives provided.
