### ISSUE TITLE
IX-Async implementation of GroupJoin possibly leading to deadlock

### ISSUE THREAD

**Issue by divega** [Reactive-Extensions/Rx.NET#182]
Heads up that this issue was reported on Entity Framework Core 1.0.0 RC2 at https://github.com/aspnet/EntityFramework/issues/5481. 

Customer provided a repro at https://github.com/iberodev/EntityFramework5481. 

We haven't tried to produce a self-contained repro with only IX-Async in the picture but we worked around it by creating our own implementation of `GroupJoin()`. 

cc @anpete

**Comment by onovotny** [comment]
Is there any chance you can submit your implementation of GroupJoin as a PR here?

**Comment by anpete** [comment]
@onovotny We rely on async/await, which, so far, IX-Async does not want to depend on.

**Comment by onovotny** [comment]
Do you recall the reason why Ix-Async has avoided async/await?

**Comment by anpete** [comment]
I think it was compat. Not sure if it still matters.

**Comment by onovotny** [comment]
If that was the reason, then a PR would be very welcome

**Comment by onovotny** [comment]
This should be fixed in #170. Can you please retest against 3.0.1-build00046 or later?
