### ISSUE TITLE
IX-Async implementation of ForEachAsync possibly failing to dipose enumerator

### ISSUE THREAD

**Issue by divega** [Reactive-Extensions/Rx.NET#183]
We got an EF Core 1.0.0 RC2 bug report at https://github.com/aspnet/EntityFramework/issues/5440 that could be explained by `ForEachAsync()` not timely calling `Dispose()` on the `IAsyncEnumerator<T>`.

We didn't get a full repro but the customers confirmed that the issue went away when we replaced IX-Async's implementation of `ForEachAsync()` with our own.

cc @anpete

**Comment by onovotny** [comment]
Is there any chance you can submit your version as a PR?

**Comment by onovotny** [comment]
This should be fixed in #170. Can you please verify with 3.0.1-build00046 or later?
