### ISSUE TITLE
Ship Rx/Ix 3.0

### ISSUE THREAD

**Issue by onovotny** [Reactive-Extensions/Rx.NET#184]
This issue is meant to serve as a checklist for shipping Ix and Rx 3.0. 

- [x] Update licenses to .NET Foundation. NuSpec's and source files. Also fixes #23 (Oren)
- [x] Sanity check latest packages against all supported project types. Ensure NuGet's can be installed and correct versions are referenced
- [x] Set up authenticode signing infrastructure (Martin)
- [x] Authenticode sign final version
- [x] Update Go Links in nuspecs (Martin)
- [x] Set up CI build (Oren)

**Comment by onovotny** [comment]
Note that the builds all show an NU1007 warning. This is a bug in the CLI tools and is tracked here:
https://github.com/dotnet/cli/issues/3381

**Comment by mattpodwysocki** [comment]
@onovotny we should at some point start splitting out Ix and Rx into two separate repos so we can version them separately.

**Comment by onovotny** [comment]
@mattpodwysocki that would seem to best fit in with moving to the `ReactiveX` org. The only downside is potentially losing history.

I can also see an option: push this repo to both the new Ix and Rx repo and then delete the corresponding directories in the destination.

**Comment by mattpodwysocki** [comment]
@onovotny I think we should do it sooner rather than later.  Yes, that was the biggest issue when dealing with this before was to tease out the history for each commit whether it be for Ix or Rx when we went to GitHub in the first place

**Comment by martinwoodward** [comment]
When we decide we want to do that, I could probably rustle up some git filter-branch magic that would give us a new repo of just the IX and RX trees with history for those folders. But let's ship a signed 3.0 first :)

**Comment by onovotny** [comment]
@martinwoodward that could be slick. Yeah, I think we can/should do it just after shipping 3.0. Are there any magic tools for moving issues or do we just manually copy/reference them?

**Comment by martinwoodward** [comment]
No magic there I'm afraid. We'd probably just reference - use the move to make a clean start and pull over the essential issues.

**Comment by mattpodwysocki** [comment]
@martinwoodward sounds familiar when we moved from Codeplex...

**Comment by onovotny** [comment]
Is there any reason to have `requireLicenseAcceptance` on the NuGet package set to `true` anymore?

**Comment by mattpodwysocki** [comment]
@onovotny no, that was because we had a custom license. We should be Apache 2.0 all the way around

**Comment by onovotny** [comment]
Should `authors` remain as `Microsoft` or also move to `.NET Foundation and Contributors`?

**Comment by martinwoodward** [comment]
Def not Microsoft. `.NET Foundation and Contributors` would be ok, if you wanted to pull out the main committers from history that might be a nice thing to do but not very future proof.

**Comment by martinwoodward** [comment]
I have updated where the FWLinks point to that are used in the current codebase:

| ID     | Original URL | New URL |
|--------|--------------|---------|
| 261276 | http://msdn.microsoft.com/en-us/data/gg577609 | http://reactivex.io/ |
| 261274 | http://i.msdn.microsoft.com/en-us/data/gg577609.Logo(en-us,MSDN.10).png | http://i.msdn.microsoft.com/en-us/data/gg577609.Logo(en-us,MSDN.10).png |
| 261273 | http://rx.codeplex.com | https://github.com/Reactive-Extensions/Rx.NET |
| 261272 | http://msdn.microsoft.com/en-us/hh295787 | https://github.com/Reactive-Extensions/Rx.NET/blob/master/LICENSE |
| 201727 | http://social.msdn.microsoft.com/Forums/en-US/rx/threads | http://reactivex.io/community.html |
| 179929 | http://msdn.microsoft.com/en-us/data/gg577609 | http://reactivex.io/ |

Let me know if I missed any or we have a better location for them to go to.

We probably want to update http://reactivex.io/community.html at some point.

**Comment by onovotny** [comment]
Sanity check turned up a NuGet regression #193

**Comment by LeeCampbell** [comment]
Can I add a request here related to builds, before this issue is closed. After a running _.\build.ps1_ I think the git repo should be still considered clean. Currently after running this build script (assuming this is what I am supposed to do), I end up with a dirty repo with 90 modified _AssemblyInfo.cs_ files.

Ideas on how to avoid this:

 * xcopy the code base to _working_ directory that is git ignored and execute the build from there. (as per how JSON.NET build works)
 * Have a linked `AssemblyInfo.g.cs` file that is git ignored
 * Use some build magic to set these values from the command line instead of in the file.
 * check in the most recent version of these files?

**Comment by onovotny** [comment]
@LeeCampbell fixed in https://github.com/Reactive-Extensions/Rx.NET/commit/93d9f19f8e9aeb41ee63f076bd58383f0353dbb5. The tree should be clean after build now.

**Comment by LeeCampbell** [comment]
Thanks. Looks good now

**Comment by onovotny** [comment]
Looking for sign-off here to tag https://github.com/Reactive-Extensions/Rx.NET/commit/327d7bdac1e2cbc2cb8751848f63480c84cdd8be as 3.0 from @bartdesmet @mattpodwysocki and @shiftkey. I believe we're now code-complete.

**Comment by bartdesmet** [comment]
Looks good.

**Comment by mattpodwysocki** [comment]
Good to go for me

**Comment by onovotny** [comment]
Status update: have tagged the commit and have the unsigned binaries/packages. We ran into an issue with the tool used to repack the nupgks after singning. @martinwoodward is working on a workaround. Will have signed binaries posted shortly.

**Comment by onovotny** [comment]
The final signed 3.0 binaries are on the MyGet feed and will be live on NuGet.org on the 27th.
