### ISSUE TITLE
How can we access the old packages?

### ISSUE THREAD

**Issue by DamianReeves** [Reactive-Extensions/Rx.NET#211]
All the pre-3.0 packages are gone. How can we access these packages? I'm trying to use it from LINQPad so it might just be a tool issue as I know nuget doesn't really delete anything, it just de-lists it.

**Comment by onovotny** [comment]
We have hidden the old packages to prevent confusion when browsing NuGet. As you note, they're not really gone so existing usages, or new usages that explicitly state the name/version, will continue to work. 

The recommendation is to switch over to the 3.0 packages as soon as possible as that's where all the future work lies.

Thanks

**Comment by DamianReeves** [comment]
Thanks. Excited to see this transition actually happening.
