### ISSUE TITLE
Where can I find the Interval and Timer operators in Rx 3.0?

### ISSUE THREAD

**Issue by Sathyaish** [Reactive-Extensions/Rx.NET#214]
I can't find the Timer and Interval operators in Rx 3.0. Have they been removed? I found the Interval operator particularly useful to create a timespan between enumerable elements.

Am I missing something?

**Comment by onovotny** [comment]
They should be present:
https://github.com/Reactive-Extensions/Rx.NET/blob/master/Rx.NET/Source/System.Reactive.Linq/Reactive/Linq/Observable.Time.cs#L1726

What packages are you referencing and how are you trying to use it?

**Comment by Sathyaish** [comment]
I installed the System.Reactive package into my console application in Visual Studio 2015 and now I do not see them. Please see the picture below.

![apimissing](https://cloud.githubusercontent.com/assets/7037893/16564599/fccb76d0-4225-11e6-9224-eac099a8ca18.png)

They were present until a week ago when I used the NuGet package manager to get Rx-Main. That got me v2.2.5 of the assembly.

However, now when I search NuGet for Rx-Main, it doesn't turn up in the results. I infer that is due to the announcement on 16th June that Rx was made a part of the .NET foundation and the new NuGet package was called System.Reactive.

Have these been moved?

**Comment by akarnokd** [comment]
They are still static methods on `Observable` (and not extension methods on `IObservable`:

```cs
using System.Reactive.Linq;

Observable.Interval(TimeSpan.FromSeconds(1));
Observable.Timer(TimeSpan.FromSeconds(1));
```

**Comment by Sathyaish** [comment]
Thank you. My bad.

**Comment by shiftkey** [comment]
@Sathyaish can we close this out?

**Comment by Sathyaish** [comment]
Absolutely. Please close the issue.
