### ISSUE TITLE
Package restored failed for PCL targetting .NET46 & UWP

### ISSUE THREAD

**Issue by bezysoftware** [Reactive-Extensions/Rx.NET#216]
Hi, I cannot install the System.Reactive package into PCL targetting .NET46 & UWP:

Version conflict detected for System.Collections. 
 ClassLibrary1 (>= 1.0.0) -> System.Reactive (>= 3.0.0) -> System.Reactive.PlatformServices (>= 3.0.0) -> System.Collections (>= 4.0.11) 
 ClassLibrary1 (>= 1.0.0) -> Microsoft.NETCore.Portable.Compatibility (>= 1.0.0) -> Microsoft.NETCore.Runtime (>= 1.0.0) -> Microsoft.NETCore.Runtime.CoreCLR-x86 (>= 1.0.0) -> System.Collections (= 4.0.10).
System.Reactive.Interfaces 3.0.0 is not compatible with .NETPlatform,Version=v5.0.
System.Reactive.Core 3.0.0 is not compatible with .NETPlatform,Version=v5.0.
System.Reactive.Linq 3.0.0 is not compatible with .NETPlatform,Version=v5.0.
System.Reactive.PlatformServices 3.0.0 is not compatible with .NETPlatform,Version=v5.0.
Some packages are not compatible with .NETPlatform,Version=v5.0.
Package restore failed for 'ClassLibrary1'.
Package restore failed. Rolling back package changes for 'ClassLibrary1'.

Any ideas?

**Comment by bezysoftware** [comment]
Installing Rx-main works fine

**Comment by onovotny** [comment]
Hi @bezysoftware, you need at least the 5.2.0 UWP metapackage to use any .NET Core/NET Standard libraries. My guess is that you have either 5.0.0 or 5.1.0. 

Unfortunately, they had to delist the 5.2.0 package due to a couple of bugs. There's a tracking issue here: https://github.com/dotnet/cli/issues/3189 and the referenced issues do have workarounds. I believe they'll have a fix out soon (5.2.1?)

**Comment by bezysoftware** [comment]
I see, you are right, I tried upgrading to latest UWP package (5.1.0) but that didn't help :) Didn't know 5.2.0 was pulled, thanks for letting me know

**Comment by onovotny** [comment]
The UWP 5.2.1 package has been pushed to NuGet.org. Closing this out now, please re-open if there's still an issue.

**Comment by bezysoftware** [comment]
This works now in projects targeting UWP alone, but in a PCL targeting UWP + NET4.6 I'm still not able to install this.

Restoring packages for 'ClassLibrary1'.
Restoring packages for c:\users\bezysoftware\documents\visual studio 15\Projects\ClassLibrary1\ClassLibrary1\project.json...
Version conflict detected for System.Collections. 
 ClassLibrary1 (>= 1.0.0) -> System.Reactive (>= 3.0.0) -> System.Reactive.PlatformServices (>= 3.0.0) -> System.Collections (>= 4.0.11) 
 ClassLibrary1 (>= 1.0.0) -> Microsoft.NETCore.Portable.Compatibility (>= 1.0.0) -> Microsoft.NETCore.Runtime (>= 1.0.0) -> Microsoft.NETCore.Runtime.CoreCLR-x86 (>= 1.0.0) -> System.Collections (= 4.0.10).
System.Reactive.Interfaces 3.0.0 is not compatible with .NETPlatform,Version=v5.0.
System.Reactive.Core 3.0.0 is not compatible with .NETPlatform,Version=v5.0.
System.Reactive.Linq 3.0.0 is not compatible with .NETPlatform,Version=v5.0.
System.Reactive.PlatformServices 3.0.0 is not compatible with .NETPlatform,Version=v5.0.
Some packages are not compatible with .NETPlatform,Version=v5.0.
System.Linq.Expressions 4.1.0 provides a compile-time reference assembly for System.Linq.Expressions on DNXCore,Version=v5.0, but there is no run-time assembly compatible with win7-x86.
System.Linq 4.1.0 provides a compile-time reference assembly for System.Linq on DNXCore,Version=v5.0, but there is no run-time assembly compatible with win7-x86.
System.Net.NetworkInformation 4.0.0 provides a compile-time reference assembly for System.Net.NetworkInformation on DNXCore,Version=v5.0, but there is no run-time assembly compatible with win7-x86.
System.Text.RegularExpressions 4.1.0 provides a compile-time reference assembly for System.Text.RegularExpressions on DNXCore,Version=v5.0, but there is no run-time assembly compatible with win7-x86.
Some packages are not compatible with DNXCore,Version=v5.0 (win7-x86).
System.Linq.Expressions 4.1.0 provides a compile-time reference assembly for System.Linq.Expressions on DNXCore,Version=v5.0, but there is no run-time assembly compatible with win7-x64.
System.Linq 4.1.0 provides a compile-time reference assembly for System.Linq on DNXCore,Version=v5.0, but there is no run-time assembly compatible with win7-x64.
System.Net.NetworkInformation 4.0.0 provides a compile-time reference assembly for System.Net.NetworkInformation on DNXCore,Version=v5.0, but there is no run-time assembly compatible with win7-x64.
System.Text.RegularExpressions 4.1.0 provides a compile-time reference assembly for System.Text.RegularExpressions on DNXCore,Version=v5.0, but there is no run-time assembly compatible with win7-x64.
Some packages are not compatible with DNXCore,Version=v5.0 (win7-x64).
Package restore failed for 'ClassLibrary1'.
Package restore failed. Rolling back package changes for 'ClassLibrary1'.
========== Finished ==========

**Comment by bezysoftware** [comment]
If the PCL package targets 4.5.1 + UWP it works

**Comment by onovotny** [comment]
Can you post your project.json file? Something is wrong in it as there shouldn't be any `dnxcore50` references in it anymore.

**Comment by bezysoftware** [comment]
{
"supports": {
"net46.app": {},
"uwp.10.0.app": {}
},
"dependencies": {
"Microsoft.NETCore": "5.0.0",
"Microsoft.NETCore.Portable.Compatibility": "1.0.0"
},
"frameworks": {
"dotnet": {
"imports": "portable-net452+win81"
}
}
}

This is what it looks like right after creating the PCL project

**Comment by onovotny** [comment]
That looks like the "old" PCL project template. I'll file a bug/blog about the fact you really shouldn't be using this method anymore.

My suggestion is to right-click the project and click the "Target .NET Platform Standard" instead. You can use 1.3 for net46+ or net 1.4 for .net 4.6.1+. Either support UWP.

Then, remove the contents of the supports section and make sure to use the netstandard.library 1.6.0 metapackage.

In your UWP project, use the 5.2.2 version of the UWP package to use any netstandard-based library.

**Comment by bezysoftware** [comment]
Ok, but how does it then work with libs which don't target netstandard? (e.g. Lex.db, mvvm light libs...) 
I found out I can simply add an imports section into my project.json  which allows to pkg to install, but is that the right thing to do?

**Comment by onovotny** [comment]
Adding an imports statement is usually the wrong thing to do -- it's there as an escape hatch/compatibility mechanism.

What are you trying to do?

**Comment by bezysoftware** [comment]
That was more a general question - as a lib author, what are my options when I want to switch to netstandard, but some of the packages I depend on are not targeting netstandard, only old PCL profiles. 

One such lib I have is FirebaseDatabase.net - for streaming changes I use Rx, for offline data persistence I use Lex.DB (EF feels like an overkill, I need something super simple, which Lex.DB is). Currently it is a PCL lib, but I would like to target netstandard, but can't because lex.DB doesn't have netstandard versiom (yet).

**Comment by bezysoftware** [comment]
But as for the original combination of UWP + NET46 - I use this in my apps to make the common platform-independent parts unit-testable in a traditional Unit Test Project, which targets .net 4.6. Otherwise I would have to use the UWP Test Project which cannot use any of the mocking frameworks

**Comment by onovotny** [comment]
To answer your issue, it's still the wrong set of targets/based off an old template. I'd recommend creating a new portable class library project and then switching it to a .NET Standard based PCL (there's no file->new template for it). Be sure to use the regular portable class library project type, not the .NET Core specific ones (your project file should be a csproj).

My blog post has details:
https://oren.codes/2016/06/23/portable-is-dead-long-live-netstandard/

From there, you can reference your project from any compatible project type -- UWP can target NET Standard 1.4 and earlier; .NET 4.6 can do 1.3 (.net 4.6.1 can do 1.4).

For your UWP project, just make sure you use the 5.2.2 version of the Microsoft.NETCore.UniversalWindowsPlatform package as that's the one required when using .net standard-based libraries.
