### ISSUE TITLE
Remove granular package dependencies

### ISSUE THREAD

**Issue by onovotny** [Reactive-Extensions/Rx.NET#217]
As per the current guidance from @yishaigalatzer, the NuGet team and the BCL team, .NET Standard packages should have a dependency on the `NETStandard.Library` version, not the individual packages.

**Comment by shiftkey** [comment]
> As per the current guidance

Is this guidance linkable somewhere?

**Comment by onovotny** [comment]
@shiftkey nope, trying to get that out of @yishaigalatzer
