### ISSUE TITLE
LocalScheduler work stealing bug

### ISSUE THREAD

**Issue by mattpodwysocki** [Reactive-Extensions/Rx.NET#22]
I discovered a bug in the LocalScheduler which is affecting one of our applications. The app makes use of ThreadPoolScheduler and DispatcherScheduler, which both inherit from the LocalScheduler base class. I have attached a minimal source file which duplicates the problem. If everything worked as expected, the program should print "GUI" and "THREADPOOL" forever. Instead, it will eventually print the "FAIL!" message. 

 The "FAIL!" case arises when LocalScheduler.ExecuteNextShortTermWorkItem runs on the ThreadPoolScheduler, but 'next' (the result of s_shortTerm.Dequeue) is a DispatcherScheduler WorkItem. In other words, the running thread is a ThreadPool thread (and 'scheduler' is a ThreadPoolScheduler), but 'next'._scheduler is a DispatcherScheduler. The appearance of the bug is also sensitive to the size of the application's delays relative to to the size of LocalScheduler.RETRYSHORT (which is currently 50 ms). 

 I'm not sure what is the best way to fix this. One way is to convert s_shortTerm and the related data structures into instance variables rather than static variables. That will keep the various workItems from mixing together. Another possibility is to store a separate short term set per subclass (one for DispatcherScheduler, one for ThreadPoolScheduler, etc). A third possibility is to make ExecuteNextShortTermWorkItem use 'next'._scheduler to run the work, but I'm not sure if that causes other problems (excessive delays, ordering issues, etc). 

Program.cs
```c#
using System;
using System.Diagnostics;
using System.Reactive.Concurrency;
using System.Windows;
using System.Windows.Threading;


namespace RxSandbox4 {
  public class ModelObject : DependencyObject {
    public void Start() {
      Schedule();
    }

    private void Schedule() {
      var now=DateTimeOffset.Now;
      const int dispatcherDelay=55;
      const int threadPoolDelay=60;
      new DispatcherScheduler(Dispatcher, DispatcherPriority.SystemIdle)
        .Schedule(now.Add(TimeSpan.FromMilliseconds(dispatcherDelay)), RunMeOnGui);
      ThreadPoolScheduler.Instance
        .Schedule(now.Add(TimeSpan.FromMilliseconds(threadPoolDelay)), RunMeOnThreadPool);
    }

    private void RunMeOnThreadPool() {
      Debug.Print("THREADPOOl");
    }

    private void RunMeOnGui() {
      if(!CheckAccess()) {
        Debug.Print("FAIL!");
        return;
      }
      Debug.Print("GUI");
      Schedule();
    }
  }


  internal class Program {
    private static void Main(string[] args) {
      Dispatcher.CurrentDispatcher.InvokeAsync(() => {
        var model=new ModelObject();
        model.Start();
      });
      Dispatcher.Run();
    }
  }
}

```

 Please let me know if you need any more information. Thanks.

**Comment by bartdesmet** [comment]
Great catch! We have a candidate fix for this, which will be verified and tested for the next release of Rx.NET.

**Comment by mstrobel** [comment]
There appears to be an issue with your fix, namely `LocalScheduler.SystemClockChanged()` is now an instance-level handler that gets subscribed to a static event, but it is never unsubscribed.
