### ISSUE TITLE
where is all the source code?

### ISSUE THREAD

**Issue by jmagaram** [Reactive-Extensions/Rx.NET#225]
I'm looking around for the source code for the IObservable extension methods like Join, GroupJoin, Select, CombineLatest, Timeout, Delay, etc. but can't find any of it. Very confusing. I see the Source folder at the link below but no real interesting code in there. Am I looking in the wrong place?

https://github.com/Reactive-Extensions/Rx.NET/tree/master/Rx.NET/Source

**Comment by flagbug** [comment]
It's nested a bit deeper: https://github.com/Reactive-Extensions/Rx.NET/blob/53f52f935e83437ee4d36678832b648dffde9a81/Rx.NET/Source/System.Reactive.Linq/Reactive/Linq/Observable/GroupJoin.cs

**Comment by shiftkey** [comment]
What @flagbug said - the folder structure is intended to reflect the assembly structure and then the namespaces.
