### ISSUE TITLE
Update names on Create methods

### ISSUE THREAD

**Issue by onovotny** [Reactive-Extensions/Rx.NET#228]
Looking more closely at https://github.com/Reactive-Extensions/Rx.NET/pull/221, before we release a version of Ix with that API publically, I think it'd be more clear if we rename the `Create()` methods to be `Enumerator()` and `Enumerable()` as that will help readability in the code.

For example, consider this usage:
https://github.com/Reactive-Extensions/Rx.NET/blob/master/Ix.NET/Source/System.Interactive.Async/Skip.cs#L22-L54

Right now, `Create` feels too overloaded in different ways.

**Comment by shiftkey** [comment]
I kind of like `CreateEnumerator` and `CreateEnumerable` here, even if they feel a bit verbose.

cc @Yshayy @slang25 for thoughts as they were interested in making this API public in the first place...

**Comment by onovotny** [comment]
When considering the options, also consider it's a static method on `AsyncEnumerable`, so the full usages are:

`AsyncEnumerable.Enumerator()`
`AsyncEnumerable.Enumerable()`
or
`AsyncEnumerable.CreateEnumerable()`
`AsyncEnumerable.CreateEnumerator()`

**Comment by slang25** [comment]
Yeah, I definitely agree something should change, I just used it from the myget feed and my code reads:
```
AsyncEnumerable.Create(() =>
    AsyncEnumerable.Create(...
```
which looks weird. From what's being suggested I like:
```
AsyncEnumerable.CreateEnumerable()
AsyncEnumerable.CreateEnumerator()
```

Moving them is not a bad option either, but abbreviating doesn't make sense to me.

My underlying reasons for wanting these api's is that so I can myself add the init* functions found in the [F# AsyncSeq equivalent](http://fsprojects.github.io/FSharp.Control.AsyncSeq/reference/fsharp-control-asyncseq.html), the init* functions are incredibly useful, and it's this opens this up for people to start using with minimal friction.
