### ISSUE TITLE
NuGet packages don't use the Apache 2 license

### ISSUE THREAD

**Issue by mattpodwysocki** [Reactive-Extensions/Rx.NET#23]
Copied from https://rx.codeplex.com/workitem/70

The Rx, Ix, and other related packages in NuGet (such as  http://www.nuget.org/packages/Rx-Main/) 
 has the link to the license page. 

 However it refers to  http://go.microsoft.com/fwlink/?LinkID=261272, not Apache License. 

 According to the license page in this project site (https://rx.codeplex.com/license), all resources by 
 this project are licensed under the Apache License 2.0, and I had found no exception clause. 

 I think that the link to the license page of NuGet packages might be a mistake and should be fixed, or 
 if this is correct, the notice of special licensing for NuGet packages should be mentioned in this project site.

**Comment by ZycaR** [comment]
+1 to fix this issue as soon as possible ... elsewhere it's useless for further usage.
(only as part of your non-public / personal projects)

Please be so kind and fix, it should not be that hard .. and it's know issue for several months.

**Comment by drogba35** [comment]
Fixing this issue would make my life so much easier. 

Pls fix, thx

**Comment by onovotny** [comment]
Fixed in master now
