### ISSUE TITLE
NullReferenceException in VirtualTimeScheduler.GetNext()

### ISSUE THREAD

**Issue by mattpodwysocki** [Reactive-Extensions/Rx.NET#24]
Copied from https://rx.codeplex.com/workitem/72

We are using Rx "2.1.30214.0" with "net40" and got a NullReferenceException on a production machine - all we know is, that the NRE was caught but our recovery attempt failed... 
```
 ---> (Interne Ausnahme #0) System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt. 
 bei System.Reactive.Concurrency.VirtualTimeScheduler2.GetNext() 
 bei System.Reactive.Concurrency.VirtualTimeSchedulerBase2.Start() 
 bei ...OurCustomScheduler.Worker() in d:\Build...\OurCustomScheduler.cs:Zeile 70. 
 bei System.Threading.Tasks.Task.InnerInvoke() 
 bei System.Threading.Tasks.Task.Execute()<--- 
```
Our scheduler is derived from VirtualTimeScheduler<,> ...
    `class OurCustomScheduler : VirtualTimeScheduler<DateTime, ulong>, IDisposable { ... }`

...and its main purpose is to run a Worker with
   `Task.Factory.StartNew(Worker, TaskCreationOptions.LongRunning);`

...that will advance the (virtual) time eventually which will result in a call to `VirtualTimeScheduler.GetNext()` to execute the next item(s). It is used like that:
```c#
subscription = Observable
                        .Interval(cycle, scheduler) // OurCustomScheduler
                        .Subscribe(...);
```
However, a NRE is thrown inside GetNext() and when we try a restart to recover
```c#
   // recovery:
   log.Message("Restarting scheduler.").Info();
   Stop();
   Start();
```
...the call to `VirtualTimeSchedulerBase.Start()` calls `GetNext()` again resulting in another NRE as the problem persisted. 

 The `GetNext()` method does not contain much code - any ideas what caused the NullReferenceException? 
 (The queue is readonly...)
```c#
protected override IScheduledItem<TAbsolute> GetNext()
    {
      while (this.queue.Count > 0)
      {
        ScheduledItem<TAbsolute> scheduledItem = this.queue.Peek();
        if (!scheduledItem.IsCanceled)
          return (IScheduledItem<TAbsolute>) scheduledItem;
        this.queue.Dequeue();
      }
      return (IScheduledItem<TAbsolute>) null;
    }
```

**Comment by bartdesmet** [comment]
This has now been fixed by making VirtualTimeScheduler thread-safe.
