### ISSUE TITLE
Build problems: Framework not installed: WindowsPhoneApp, version=v8.1

### ISSUE THREAD

**Issue by akarnokd** [Reactive-Extensions/Rx.NET#245]
I'm trying to build the Rx.NET.sln from Visual Studio Community 14 u 3.1 (running on Windows 7 x64) but get the error above.

I get that I'm supposed to install that framework but I was unable to find a way to do it. Some articles indicate it's part of the VS installer but I didn't see any trace of it. 

Do I need VS full to build Rx.NET?

**Comment by danielcweber** [comment]
Try running the installer, choose "modify" and select "Windows 8.1 and Windows Phone 8.0/8.1 Tools".

**Comment by akarnokd** [comment]
This is what I see in the installer:

![image](https://cloud.githubusercontent.com/assets/1269832/17437147/358a633c-5b1c-11e6-9e26-b0f9b5fad880.png)

**Comment by danielcweber** [comment]
VS 14 means 2015 right? Do you have Update 3 installed?

**Comment by akarnokd** [comment]
Yes, update 3.1 in fact:

![image](https://cloud.githubusercontent.com/assets/1269832/17437272/07be1fc4-5b1d-11e6-8e54-40c036255918.png)

Also it is the **community** version as I mentioned before.

**Comment by danielcweber** [comment]
Interesting. You could try installing [Windows 8 SDK](https://www.microsoft.com/en-US/download/details.aspx?id=35471) manually.

**Comment by onovotny** [comment]
I don't believe you'll be able to build this on Windows 7 -- the Windows Phone 8/RT stuff can't be installed there.

I'm fairly sure you'll want/need to be on Windows 10 to build this.

**Comment by onovotny** [comment]
Which project are you getting this with BTW, as the xproj stuff should be pulling down private targeting packs for this stuff. I didn't think any local special targets were needed.

**Comment by akarnokd** [comment]
The [Rx.NET.sln](https://github.com/Reactive-Extensions/Rx.NET/blob/master/Rx.NET/Source/Rx.NET.sln).

**Comment by akarnokd** [comment]
I don't really need wpa81 but running tests will build and fail the project and not sure if it actually runs my code changes .

**Comment by onovotny** [comment]
Which project within that solution is failing though? There's are many projects in there.

**Comment by akarnokd** [comment]
These:

```
2>  Project System.Reactive.Core (WindowsPhoneApp,Version=v8.1) will be compiled because project is not safe for incremental compilation. Use --build-profile flag for more information.
2>  Compiling System.Reactive.Core for WindowsPhoneApp,Version=v8.1
2>C:\Users\akarnokd\Source\Repos\Rx.NET\Rx.NET\Source\System.Reactive.Core\project.json(156,14): error DOTNET1011: Framework not installed: WindowsPhoneApp,Version=v8.1 in
2>  Compilation failed.
2>      0 Warning(s)
2>      1 Error(s)
2>  Time elapsed 00:00:00.0003455

10>  Compiling System.Reactive.WindowsRuntime for WindowsPhoneApp,Version=v8.1
10>C:\Users\akarnokd\Source\Repos\Rx.NET\Rx.NET\Source\System.Reactive.WindowsRuntime\project.json(31,14): error DOTNET1011: Framework not installed: WindowsPhoneApp,Version=v8.1 in
10>  Compilation failed.
10>      0 Warning(s)
10>      1 Error(s)
10>  Time elapsed 00:00:00.0074985

6>  Compiling System.Reactive.Windows.Forms for .NETFramework,Version=v4.6
4>C:\Users\akarnokd\Source\Repos\Rx.NET\Rx.NET\Source\System.Reactive.Windows.Threading\project.json(54,14): error DOTNET1011: Framework not installed: WindowsPhoneApp,Version=v8.1 in
4>  Compilation failed.
4>      0 Warning(s)
4>      1 Error(s)
4>  Time elapsed 00:00:00.0021220

7>  Compiling System.Reactive.PlatformServices for WindowsPhoneApp,Version=v8.1
7>  Compilation failed.
7>      0 Warning(s)
7>      1 Error(s)
7>  Time elapsed 00:00:00.0017136

11>  Compiling Microsoft.Reactive.Testing for WindowsPhoneApp,Version=v8.1
11>C:\Users\akarnokd\Source\Repos\Rx.NET\Rx.NET\Source\Microsoft.Reactive.Testing\project.json(125,14): error DOTNET1011: Framework not installed: WindowsPhoneApp,Version=v8.1 in
11>  Compilation failed.
11>      0 Warning(s)
11>      1 Error(s)
11>  Time elapsed 00:00:00.0004365
```

**Comment by onovotny** [comment]
Interesting that it's only complaining about the `wpa81` ones and not the `netcore451` or `uap10.0` ones.

The project.json has this:

```json
"wpa81": {
      "buildOptions": {
        "define": [
          "NO_EVENTARGS_CONSTRAINT",
          "HAS_EDI",
          "HAS_WINRT",
          "HAS_PROGRESS",
          "PREFER_ASYNC",
          "HAS_AWAIT",
          "NO_REMOTING",
          "NO_SERIALIZABLE",
          "NO_THREAD",
          "CRIPPLED_REFLECTION",
          "USE_TIMER_SELF_ROOT",
          "WINDOWS",
          "WINDOWS81"
        ]
      },
      "dependencies": {
        "Microsoft.TargetingPack.Private.WinRT": {
          "version": "1.0.1",
          "type": "build"
        },
        "Microsoft.TargetingPack.Private.WindowsPhone.v8.1": {
          "version": "1.0.1",
          "type": "build"
        }
      }
    }
```
It should not require any specific SDK's because we're pulling in the dependencies we need from our private targeting pack.

Given that the error appears to be coming from the dotnet CLI, there's not much we can do here if they're checking that the SDK is installed. In that case, I'm fairly sure you'll need to be on at least Windows 8.1 to install the required SDK.

**Comment by akarnokd** [comment]
Too bad, thanks anyway. Maybe I'll just comment out those entries locally and not committing it with the actual changes.
