### ISSUE TITLE
Relaying values from more than one observable using a Subject<T> does not work if the subject subscribes to the sources or observes them on the same thread

### ISSUE THREAD

**Issue by Sathyaish** [Reactive-Extensions/Rx.NET#249]
If we use a subject to subscribe to two or more observables and propagate the values from those observables to the observers of the subject, only the values of the first observable are propagated to the observers; the values from observables other than the first observable are not propagated. This happens only if the subject subscribes to and observes values from all the observables on the current thread.

If, however, the subject subscribes to the source observables on any other thread, for e.g. using the task pool or the thread pool schedulers or a new thread scheduler, the values all the observables are propagated.

To illustrate, please consider the code snippet below.

```
using System;
using System.Reactive.Subjects;
using System.Reactive.Linq;
using System.Diagnostics;
using System.Threading;
using System.Reactive.Concurrency;

namespace FourStepsUsingSubject
{
    class Program
    {
        static void Main(string[] args)
        {
            Demo();

            Console.WriteLine("Press any key to exit the program...");
            Console.ReadKey();
        }

        static void Demo()
        {
            // Using a subject as a broadcast or relay service
            // That is, a mediator that subscribes to many observables
            // and then relays its values to its observers
            var subject = new Subject<string>();

            var s1 = subject.Subscribe(Program.PrintToConsole);
            var s2 = subject.Subscribe(Program.PrintToDebugWindow);
            var s3 = subject.Subscribe(Program.PrintToConsoleSlowly);

            var o1 = new[] { "Hello", "World" }.ToObservable();
            var o2 = new[] { "Sunday", "Monday", "Tuesday" }.ToObservable();

            // Only proagates o1's values. Does not proagate o2's values
            //var s4 = o1.ObserveOn(Scheduler.CurrentThread).Subscribe(subject);

            // Only proagates o1's values. Does not proagate o2's values
            //var s4 = o1.ObserveOn(Scheduler.Immediate).Subscribe(subject);

            // Propagates both o1's and o2's values
            //var s4 = o1.ObserveOn(Scheduler.Default).Subscribe(subject);

            // Only proagates o1's values. Does not proagate o2's values
            var s4 = o1.Subscribe(subject);

            var s5 = o2.Subscribe(subject);

            Console.WriteLine("\nPress any key to dispose all subscriptions.");
            s1.Dispose();
            s2.Dispose();
            s3.Dispose();
            s4.Dispose();
            s5.Dispose();
        }

        static void PrintToConsole(string message)
        {
            Console.WriteLine(message);
        }

        static void PrintToConsoleSlowly(string message)
        {
            Thread.Sleep(500);
            Console.WriteLine(message + " slowly...");
        }

        static void PrintToDebugWindow(string message)
        {
            Debug.Print(message);
        }
    }
}
```

I will rework it into a unit test and submit a pull request at my earliest convenience.

**Comment by akarnokd** [comment]
You doesn't seem to subscribe to `o2` before the line `var s5 = o2.Subscribe(subject);` so `subject` can't propagate that it is not receiving.

**Comment by akarnokd** [comment]
`o1` brings the `subject` to a terminal state so it won't propagate anything else. You'd want to concatenate `o1` with `Never` to make it work synchronously.

**Comment by Sathyaish** [comment]
@akarnokd I am not sure I understand what you are saying. I am subscribing to both `o1` and `o2`. So, I should receive values from both in the subject?

**Comment by Sathyaish** [comment]
> o1 brings the subject to a terminal state so it won't propagate anything else. You'd want to concatenate o1 with Never to make it work synchronously.

That seems more likely the issue here. Thank you. I'll verify and close this issue.

**Comment by akarnokd** [comment]
Use `Merge(o1, o2).subscribe(subject)` to get both.

**Comment by Sathyaish** [comment]
> Use Merge(o1, o2).subscribe(subject) to get both.

I am not really trying to do anything other than read the source code and try out little programs to learn Rx thoroughly. I know I can use lots of stuff here. `Concat`, `Merge`, `CombineLatest`, `Zip (though it will trim to the earliest one's completion)`.

You were right about the first observable putting the subject in a terminal state. That was it. How could I have overlooked that? Thank you. Case solved. :-)
