### ISSUE TITLE
NullReferenceException in TestScheduler

### ISSUE THREAD

**Issue by mattpodwysocki** [Reactive-Extensions/Rx.NET#25]
Copied from https://rx.codeplex.com/workitem/79

Using version 2.2.4.0 with .net 4.5.1. 

`TestScheduler` throws a NullReferenceException when using it with multi-threaded access, however this is not in the `TestScheduler` itself, but the `VirtualTimeScheduler`. 

 Scenario: One thread is responsible for advancing the scheduler, the other threads are responsible for yielding and sleeping on that scheduler. A reproducible test environment, either in a unit test or a console app, shows that it happens irregularly and that the scheduler is not disposed when this happens. 

 It seems likely that this is related to  #72, but as it occurs when using `TestScheduler` and not `VirtualTimeScheduler` I have logged it separately. 

 Stack trace below. 
```
System.AggregateException: One or more errors occurred. ---> System.NullReferenceException: Object reference not set to an instance of an object.
Result StackTrace:  
at System.Reactive.Concurrency.VirtualTimeScheduler`2.GetNext()
   at System.Reactive.Concurrency.VirtualTimeSchedulerBase`2.AdvanceTo(TAbsolute time)
   at System.Reactive.Concurrency.VirtualTimeSchedulerBase`2.AdvanceBy(TRelative time)
```

**Comment by bartdesmet** [comment]
This has now been fixed by making VirtualTimeScheduler thread-safe.
