### ISSUE TITLE
Where are the conditional compilation symbols defined?

### ISSUE THREAD

**Issue by Sathyaish** [Reactive-Extensions/Rx.NET#252]
Which part of the code defines the conditional compilation symbols used in the source? Since many symbols are platform-dependent, I am assuming it is some task within an MS Build file that sets them. Sorry if my question is a bit stupid. I was just curious about where I might find them.

**Comment by shiftkey** [comment]
@Sathyaish have a look at the framework targets defined in the `project.json`

For example: https://github.com/Reactive-Extensions/Rx.NET/blob/master/Rx.NET/Source/System.Reactive.Linq/project.json

**Comment by Sathyaish** [comment]
@shiftkey Awesome! Beautiful. Thank you, :-)
