### ISSUE TITLE
Why do you call it the EventLoopScheduler?

### ISSUE THREAD

**Issue by Sathyaish** [Reactive-Extensions/Rx.NET#254]
Why did you name the `EventLoopScheduler` so? The name tends to confuse.

**Comment by bartdesmet** [comment]
It's running a loop that processes events. Names are always debatable and tend to have a history (e.g. Amb) or use a domain-specific nomenclature (e.g. BehaviorSubject).

**Comment by Sathyaish** [comment]
Many thanks, @bartdesmet. I understand what you're saying but haven't had a chance to revisit the event loop scheduler code, and think of it in this light and then mentally resolve this question for myself. I'll do that later, but thanks so much for the reply. :-)

Thanks for closing the issue, @onovotny and sorry about having left it open for quite a while. :-)
