### ISSUE TITLE
Compiler critical error with RX on windows phone

### ISSUE THREAD

**Issue by mattpodwysocki** [Reactive-Extensions/Rx.NET#26]
Copied from https://rx.codeplex.com/workitem/78

Compiled with VS 2012, with project type WP 8.0 the following code will fail if debugger is not attached. 

 Somehow, if debugger not attached, compiler optimizations ruins the code inside Crash() - see comments in code. 

 Tested on Lumia 1520 (8.1), Lumia 630 (8.0).
```c#
public partial class MainPage : PhoneApplicationPage
{
    public MainPage()
    {
        InitializeComponent();
        Button.Tap += (sender, args) => new A<B, string>(new B(), "string").Crash();
    }
}

public class B
{
    public void Foo<T>(T val) { }
}

public class A<T1, T2> where T1 : B
{
    private T1 _t1;
    private T2 _t2;

    public A(T1 t1, T2 t2)
    {
        _t2 = t2;
        _t1 = t1;
    }

    public void Crash()
    {
        var obs = Observable.Return(_t2);
        obs.Subscribe(result =>
        {
            //CLR is expecting T2 to be System.String here,
            //but somehow, after passing through Observable
            //T2 here is not a string, it's A<T1, T2>

            new List<T2>().Add(result);
        });

        //Will run normally if commented
        _t1.Foo(new object());
    }
}
```

**Comment by bartdesmet** [comment]
I wasn't able to repro this. Do you have a .zip file of a project you can share? Also, is it possible to eliminate the Rx dependency? Naively it'd seem that any IObservable<T> - no matter where it comes from (i.e. using Observable.Return or not) would cause the same issue.
