### ISSUE TITLE
2.x packages missing from nuget.org

### ISSUE THREAD

**Issue by clausndk** [Reactive-Extensions/Rx.NET#260]
It seems all packages with the old naming has been removed from nuget.org, i.e.:
https://www.nuget.org/packages/Rx-Core/

I can understand the renaming of packages, but I cannot see why the old packages are removed from the feed?

Please advice, since I'm sure we are not the only ones not able to upgrade to v3 in a heartbeat. Right now we need to fix a bug and cannot redownload the package..

**Comment by danielcweber** [comment]
Although they are unlisted, they are not removed and will still download and install into your projects if they reference the old nuget versions.

**Comment by shiftkey** [comment]
@clausndk restoring `Rx-*` packages are unaffected by this change, and you can still install the old packages by specifying the version number explicitly.

>  Right now we need to fix a bug and cannot redownload the package..

Please provide more details about this scenario - in particular what version of NuGet you are using.

**Comment by clausndk** [comment]
Our scenario is that we are refactoring a setup, where a component now needs the 2.x version and have not needed it before.

Am I missing something?

**Comment by danielcweber** [comment]
You will probably not be able to add the 2.x to a project through the NuGet extension. You may need to add the packages manually in your packages.config and reference the correct dlls from the packages folder in your csproj. Are you familiar with those concepts, do you have working projects where you can copy the imports from ?

**Comment by clausndk** [comment]
Yes, I am and will try it. Thanks!

**Comment by danielcweber** [comment]
After manually adding the packages, do a complete package restore. It should work.

**Comment by clausndk** [comment]
It works, thanks!

**Comment by KenticoDevTrev** [comment]
This is a HUGE issue for us as well.  Kentico uses LinqtoTwitter version 4 which used the RX libraries, and we cannot do a package-update -reinstall anymore because they are unlisted, only if we had the previous files in the project folder can it be restored.  I also understand the renaming, but please put back the version 2.0 up there!!
