### ISSUE TITLE
Problem with nuget on buildserver

### ISSUE THREAD

**Issue by GreenEyedAndy** [Reactive-Extensions/Rx.NET#276]
I really want to use the Reactive-Extensionss, but I have great problems with nuget on my buildserver.
We still use version 2.8.50926.602 cause the v3 handles the update-package command different from v2.x (see closed, but not fixed, issue 1490 for nuget on github).
With v2.8.x we get the following error:
>Nuget restore -----------------------------------------
>Installing 'System.Reactive.Core 3.0.0'.
>Installing 'System.Reactive.Linq 3.0.0'.
>Installing 'System.Reactive.Interfaces 3.0.0'.
>Successfully installed 'System.Reactive.Interfaces 3.0.0'.
>'System.Reactive.Core' already has a dependency defined for 'System.Reactive.Interfaces'.
>'System.Reactive.Linq' already has a dependency defined for 'System.Reactive.Interfaces'.
>Nuget update -----------------------------------------
>In "Packages" wird nach installierten Paketen gesucht.
>"xxx" wird aktualisiert...
>The 'System.Reactive.Interfaces 3.0.0' package requires NuGet client version '2.12' or above, but the >current NuGet version is '2.8.50926.602'.

But there is no commandline version of v.2.12.

Please help.

**Comment by BryantL** [comment]
3.4.4 works but since you want to stay on 2.x then get the nuget commandline package (https://www.nuget.org/packages/NuGet.CommandLine/2.12.0) and extract the nuget.exe from there.

**Comment by GreenEyedAndy** [comment]
@BryantL thank you for your answer. You saved my day!
Version 2.12 is working and the update-command seems to behave as in version 2.8.
Then it's still a issue for nuget v3 but that's no issue for this project.
