### ISSUE TITLE
Which version / commit / tag do I need to clone in order to get the solution that had just the .csproj files?

### ISSUE THREAD

**Issue by Sathyaish** [Reactive-Extensions/Rx.NET#277]
I know this is going to make me look like an idiot, but so be that. I don't know what I don't know.

I just need to clone a version of the repository where the solution used `.csproj` files and not the new `.xproj` files. If I need that, which commit / version do I clone? Around what date was this transition made? Where do I get the old code base from?

I haven't been able to install the Visual Studio update that makes all the `xproj` files and stuff work, and I don't want to waste any more time on that. My study effort of Rx has come to a halt because of that. So, I'll just need an old copy of the code to read through and step-through.

I do have an old copy of the code but I've made so many changes to that one just to understand what's happening that stepping through that version is pretty pointless for my research.

Thank you for your help.

**Comment by shiftkey** [comment]
If you checkout the [`v2.2.5`](https://github.com/Reactive-Extensions/Rx.NET/tree/v2.2.5) tag on this repository, that should give you a [recent release](https://www.nuget.org/packages/Rx-Main/2.2.5) that was before the 3.x transition.

**Comment by Sathyaish** [comment]
Thank you, @shiftkey. I remember now that I remembered the old version and the old NuGet package name (which is now not available, but that's okay because I won't need that).

Was there a time when v3.0 also had just the `.csproj` files? I could be remembering wrong but I took a clone several times between May 2016 (when it was v2.2.5) and early July 2016, and I think (this is where I could be wrong) that sometime early July 2016, too, even though the version was v3.0, the projects used `csproj` files? Is that true?

**Comment by shiftkey** [comment]
@Sathyaish I'm really not sure, but here's what I did to find the point just before we removed the csproj files:

```
git log --oneline -n 1 -- .\Rx.NET\Source\System.Reactive.Core\System.Reactive.Core.csproj
git checkout 49783c7~1
.\build
```

**Comment by Sathyaish** [comment]
Thanks so much, @shiftkey. With your help, I was able to glide down the right path and solve this mystery.

Here is what happened.

It appears that the effort to migrate to the new `xproj` and `package.json` files began on 1st December 2015 with revision 46a02f7 in which @khellang added the `xproj` files.

However, the `csproj` files co-existed until they were removed, as you rightly pointed out, in revision 49783c7 by @onovotny on 13th June 2016 at 7:32 PM (assuming this is PST).

That had me puzzled because the last clone I took that had the `csproj` files was on the 14th June 2014, i.e. after they were deleted from the repo.

It turns out that I cloned the repo on *my* 14th June 2016 at about 2 AM my time, which is Indian Time. In PST, that would have been 13th June 2016, around 1:30 PM. That was just 6 hours before they were deleted. :-)

Then when I came back to fork the repo a few days later, they were gone. :-)

**Comment by Sathyaish** [comment]
For anyone else who wanders along this path and needs to download an older commit that has the .csproj files, here are the steps to follow:

You'll want to download the commit f698a011093617a376c7e523d3136c31260f8297.

To do that:

 1. Create an empty directory someplace in your machine and clone the main repository:

     `git clone https://github.com/Reactive-Extensions/Rx.NET.git`

 2. Go to the sub-directory that has the `.git` hidden folder. In this case, it will be the folder named `Rx.NET`.

 3. Checkout the commit f698a011093617a376c7e523d3136c31260f8297 by running the command:

     `git checkout f698a011093617a376c7e523d3136c31260f8297`

You'll get that in a detached state, which I am guessing, like me, is what you want. This means you won't want to add any code to the main repository but simply fiddle with the local download you have on your machine.
