### ISSUE TITLE
Can't create binding redirect from 2.2.5 to 3.0.0. because of public key change

### ISSUE THREAD

**Issue by jahmai** [Reactive-Extensions/Rx.NET#279]
How do we deal with this? We have 3rd party libraries that reference 2.2.5 and we use 3.0.0. Changing the public key completely defeats this useful mechanism for dealing with dependency conflicts.

**Comment by onovotny** [comment]
Hi @jahmai Unfortunately, there's not much we can do here. The key had to change because the old key was the same key the .NET Framework used which would make it impossible for the community to build their own versions.

For now, we do need the eco-system to update to 3.0.

**Comment by jahmai** [comment]
Understandable but very painful!

**Comment by glopesdev** [comment]
@clairernovotny I opened a new issue #1813 which I now realize is a duplicate of this one.

It is of course understandable the need to change the public key going forward, but it feels like from Rx v4.0.0 it would be possible to provide compatibility facades for the old Rx v2 assemblies to the new `System.Reactive.dll` signed with the .NET framework public key.

This would be a one-off release purely for backwards compatibility reasons to give legacy apps a transition path.
