### ISSUE TITLE
Small resource leak in System.Reactive.Linq.QueryLanguage.LastOrDefaultInternal

### ISSUE THREAD

**Issue by mattpodwysocki** [Reactive-Extensions/Rx.NET#28]
Copied from https://rx.codeplex.com/workitem/75

Method : `System.Reactive.Linq.QueryLanguage.LastOrDefaultInternal`
The `ManualResetEvent` used to wait for the end of the sequence should be disposed after the call to `WaitOne`

**Comment by bartdesmet** [comment]
Fixed.
