### ISSUE TITLE
PostSharp fails on Xamarin.iOS with duplicate references for System.Runtime

### ISSUE THREAD

**Issue by jahmai** [Reactive-Extensions/Rx.NET#282]
Not sure who's responsible here, but will raise the issue. When using PostSharp on a Xamarin.iOS project that references System.Reactive, it fails with this error:

1>------ Build started: Project: Intrinsic.Platform-iOS, Configuration: Debug Any CPU ------
1>  Generated session id: 059febcdcefd8f5a1969af1ad46c7b32
1>  Generated build app name: Intrinsic.PlatformiOS
1>C:\Program Files (x86)\MSBuild\Xamarin\iOS\Xamarin.iOS.Windows.After.targets(63,5): warning VSX1000: The project Intrinsic.PlatformiOS was built while disconnected from a Mac agent, so only the main assembly was compiled. Connect to a Xamarin Mac build agent to build the full application.
1>POSTSHARP : postsharp error PS0099: Unhandled exception (4.3.20.0, postsharp-net40-x86-srv.exe, CLR 4.0.30319.394802, Release): PostSharp.Sdk.CodeModel.AssemblyLoadException: Cannot find assembly 'system.runtime, version=4.0.20.0, culture=neutral, publickeytoken=b03f5f7f11d50a3a'. [Version mismatch]
1>POSTSHARP : postsharp error PS0099: ============ PostSharp Assembly Loading Log ===================
1>POSTSHARP : postsharp error PS0099: LOG: Finding the assembly with binding identity 'system.runtime, version=4.0.20.0, culture=neutral, publickeytoken=b03f5f7f11d50a3a'.
1>POSTSHARP : postsharp error PS0099: LOG: Probing location 'C:\ProgramData\PostSharp\4.3.20\bin.Release\System.Runtime.exe' because this directory was explicitly added to the search path [File Not Found].
1>POSTSHARP : postsharp error PS0099: LOG: Probing location 'C:\ProgramData\PostSharp\4.3.20\bin.Release\System.Runtime.dll' because this directory was explicitly added to the search path [File Not Found].
1>POSTSHARP : postsharp error PS0099: LOG: Probing location 'C:\ProgramData\PostSharp\4.3.20\bin.Release\System.Runtime.winmd' because this directory was explicitly added to the search path [File Not Found].
1>POSTSHARP : postsharp error PS0099: LOG: Probing location 'C:\Repository\Projects\CriticalArc\Dependencies\Intrinsic\Source\Libraries\Platform\bin\iOS\Debug\System.Runtime.exe' because this directory was explicitly added to the search path [File Not Found].
1>POSTSHARP : postsharp error PS0099: LOG: Probing location 'C:\Repository\Projects\CriticalArc\Dependencies\Intrinsic\Source\Libraries\Platform\bin\iOS\Debug\System.Runtime.dll' because this directory was explicitly added to the search path [File Not Found].
1>POSTSHARP : postsharp error PS0099: LOG: Probing location 'C:\Repository\Projects\CriticalArc\Dependencies\Intrinsic\Source\Libraries\Platform\bin\iOS\Debug\System.Runtime.winmd' because this directory was explicitly added to the search path [File Not Found].
1>POSTSHARP : postsharp error PS0099: LOG: Probing location 'C:\Repository\Projects\CriticalArc\Dependencies\Intrinsic\Source\Libraries\Platform\obj\iOS\Debug\System.Runtime.exe' because this directory was explicitly added to the search path [File Not Found].
1>POSTSHARP : postsharp error PS0099: LOG: Probing location 'C:\Repository\Projects\CriticalArc\Dependencies\Intrinsic\Source\Libraries\Platform\obj\iOS\Debug\System.Runtime.dll' because this directory was explicitly added to the search path [File Not Found].
1>POSTSHARP : postsharp error PS0099: LOG: Probing location 'C:\Repository\Projects\CriticalArc\Dependencies\Intrinsic\Source\Libraries\Platform\obj\iOS\Debug\System.Runtime.winmd' because this directory was explicitly added to the search path [File Not Found].
1>POSTSHARP : postsharp error PS0099: LOG: Probing location 'C:\Repository\Projects\CriticalArc\packages\Autofac.4.1.1\lib\netstandard1.1\System.Runtime.exe' because this directory was explicitly added to the search path [File Not Found].
1>POSTSHARP : postsharp error PS0099: LOG: Probing location 'C:\Repository\Projects\CriticalArc\packages\Autofac.4.1.1\lib\netstandard1.1\System.Runtime.dll' because this directory was explicitly added to the search path [File Not Found].
1>POSTSHARP : postsharp error PS0099: LOG: Probing location 'C:\Repository\Projects\CriticalArc\packages\Autofac.4.1.1\lib\netstandard1.1\System.Runtime.winmd' because this directory was explicitly added to the search path [File Not Found].
1>POSTSHARP : postsharp error PS0099: LOG: Probing location 'C:\Repository\Projects\CriticalArc\Dependencies\Intrinsic\Source\Libraries\Core\bin\Debug\System.Runtime.exe' because this directory was explicitly added to the search path [File Not Found].
1>POSTSHARP : postsharp error PS0099: LOG: Probing location 'C:\Repository\Projects\CriticalArc\Dependencies\Intrinsic\Source\Libraries\Core\bin\Debug\System.Runtime.dll' because this directory was explicitly added to the search path [File Not Found].
1>POSTSHARP : postsharp error PS0099: LOG: Probing location 'C:\Repository\Projects\CriticalArc\Dependencies\Intrinsic\Source\Libraries\Core\bin\Debug\System.Runtime.winmd' because this directory was explicitly added to the search path [File Not Found].
1>POSTSHARP : postsharp error PS0099: LOG: Probing location 'C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\Xamarin.iOS\v1.0\System.Runtime.exe' because this directory was explicitly added to the search path [File Not Found].
1>POSTSHARP : postsharp error PS0099: LOG: Probing location 'C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\Xamarin.iOS\v1.0\System.Runtime.dll' because this directory was explicitly added to the search path [File Not Found].
1>POSTSHARP : postsharp error PS0099: LOG: Probing location 'C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\Xamarin.iOS\v1.0\System.Runtime.winmd' because this directory was explicitly added to the search path [File Not Found].
1>POSTSHARP : postsharp error PS0099: LOG: Probing location 'C:\Repository\Projects\CriticalArc\packages\PostSharp.4.3.20\lib\portable-net4+sl5+netcore45+wpa81+wp8\System.Runtime.exe' because this directory was explicitly added to the search path [File Not Found].
1>POSTSHARP : postsharp error PS0099: LOG: Probing location 'C:\Repository\Projects\CriticalArc\packages\PostSharp.4.3.20\lib\portable-net4+sl5+netcore45+wpa81+wp8\System.Runtime.dll' because this directory was explicitly added to the search path [File Not Found].
1>POSTSHARP : postsharp error PS0099: LOG: Probing location 'C:\Repository\Projects\CriticalArc\packages\PostSharp.4.3.20\lib\portable-net4+sl5+netcore45+wpa81+wp8\System.Runtime.winmd' because this directory was explicitly added to the search path [File Not Found].
1>POSTSHARP : postsharp error PS0099: LOG: Probing location 'C:\Repository\Projects\CriticalArc\packages\PostSharp.Patterns.Common.4.3.20\lib\portable-net45+netcore45+wpa81\System.Runtime.exe' because this directory was explicitly added to the search path [File Not Found].
1>POSTSHARP : postsharp error PS0099: LOG: Probing location 'C:\Repository\Projects\CriticalArc\packages\PostSharp.Patterns.Common.4.3.20\lib\portable-net45+netcore45+wpa81\System.Runtime.dll' because this directory was explicitly added to the search path [File Not Found].
1>POSTSHARP : postsharp error PS0099: LOG: Probing location 'C:\Repository\Projects\CriticalArc\packages\PostSharp.Patterns.Common.4.3.20\lib\portable-net45+netcore45+wpa81\System.Runtime.winmd' because this directory was explicitly added to the search path [File Not Found].
1>POSTSHARP : postsharp error PS0099: LOG: Probing location 'C:\Repository\Projects\CriticalArc\packages\PostSharp.Patterns.Model.4.3.20\lib\portable-net45+netcore45+wpa81\System.Runtime.exe' because this directory was explicitly added to the search path [File Not Found].
1>POSTSHARP : postsharp error PS0099: LOG: Probing location 'C:\Repository\Projects\CriticalArc\packages\PostSharp.Patterns.Model.4.3.20\lib\portable-net45+netcore45+wpa81\System.Runtime.dll' because this directory was explicitly added to the search path [File Not Found].
1>POSTSHARP : postsharp error PS0099: LOG: Probing location 'C:\Repository\Projects\CriticalArc\packages\PostSharp.Patterns.Model.4.3.20\lib\portable-net45+netcore45+wpa81\System.Runtime.winmd' because this directory was explicitly added to the search path [File Not Found].
1>POSTSHARP : postsharp error PS0099: LOG: Probing location 'C:\Repository\Projects\CriticalArc\packages\System.Reactive.Core.3.0.0\lib\netstandard1.3\System.Runtime.exe' because this directory was explicitly added to the search path [File Not Found].
1>POSTSHARP : postsharp error PS0099: LOG: Probing location 'C:\Repository\Projects\CriticalArc\packages\System.Reactive.Core.3.0.0\lib\netstandard1.3\System.Runtime.dll' because this directory was explicitly added to the search path [File Not Found].
1>POSTSHARP : postsharp error PS0099: LOG: Probing location 'C:\Repository\Projects\CriticalArc\packages\System.Reactive.Core.3.0.0\lib\netstandard1.3\System.Runtime.winmd' because this directory was explicitly added to the search path [File Not Found].
1>POSTSHARP : postsharp error PS0099: LOG: Probing location 'C:\Repository\Projects\CriticalArc\packages\System.Reactive.Interfaces.3.0.0\lib\netstandard1.0\System.Runtime.exe' because this directory was explicitly added to the search path [File Not Found].
1>POSTSHARP : postsharp error PS0099: LOG: Probing location 'C:\Repository\Projects\CriticalArc\packages\System.Reactive.Interfaces.3.0.0\lib\netstandard1.0\System.Runtime.dll' because this directory was explicitly added to the search path [File Not Found].
1>POSTSHARP : postsharp error PS0099: LOG: Probing location 'C:\Repository\Projects\CriticalArc\packages\System.Reactive.Interfaces.3.0.0\lib\netstandard1.0\System.Runtime.winmd' because this directory was explicitly added to the search path [File Not Found].
1>POSTSHARP : postsharp error PS0099: LOG: Probing location 'C:\Repository\Projects\CriticalArc\packages\System.Reactive.Linq.3.0.0\lib\netstandard1.3\System.Runtime.exe' because this directory was explicitly added to the search path [File Not Found].
1>POSTSHARP : postsharp error PS0099: LOG: Probing location 'C:\Repository\Projects\CriticalArc\packages\System.Reactive.Linq.3.0.0\lib\netstandard1.3\System.Runtime.dll' because this directory was explicitly added to the search path [File Not Found].
1>POSTSHARP : postsharp error PS0099: LOG: Probing location 'C:\Repository\Projects\CriticalArc\packages\System.Reactive.Linq.3.0.0\lib\netstandard1.3\System.Runtime.winmd' because this directory was explicitly added to the search path [File Not Found].
1>POSTSHARP : postsharp error PS0099: LOG: Probing location 'C:\Repository\Projects\CriticalArc\packages\System.Reactive.PlatformServices.3.0.0\lib\netstandard1.3\System.Runtime.exe' because this directory was explicitly added to the search path [File Not Found].
1>POSTSHARP : postsharp error PS0099: LOG: Probing location 'C:\Repository\Projects\CriticalArc\packages\System.Reactive.PlatformServices.3.0.0\lib\netstandard1.3\System.Runtime.dll' because this directory was explicitly added to the search path [File Not Found].
1>POSTSHARP : postsharp error PS0099: LOG: Probing location 'C:\Repository\Projects\CriticalArc\packages\System.Reactive.PlatformServices.3.0.0\lib\netstandard1.3\System.Runtime.winmd' because this directory was explicitly added to the search path [File Not Found].
1>POSTSHARP : postsharp error PS0099: LOG: Probing location 'C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\Xamarin.iOS\v1.0\Facades\System.Runtime.exe' because this directory was explicitly added to the search path [File Not Found].
1>POSTSHARP : postsharp error PS0099: LOG: Found file 'C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\Xamarin.iOS\v1.0\Facades\System.Runtime.dll' with identity 'system.runtime, version=4.1.0.0, culture=neutral, publickeytoken=b03f5f7f11d50a3a, processorarchitecture=msil'.
1>POSTSHARP : postsharp error PS0099: LOG: Reference mismatch for 'C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\Xamarin.iOS\v1.0\Facades\System.Runtime.dll' [VersionMismatch].
1>POSTSHARP : postsharp error PS0099: LOG: Probing location 'C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\Xamarin.iOS\v1.0\Facades\System.Runtime.winmd' because this directory was explicitly added to the search path [File Not Found].
1>POSTSHARP : postsharp error PS0099: LOG: Probing location 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Linq\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Runtime.exe' because this directory was explicitly added to the search path [File Not Found].
1>POSTSHARP : postsharp error PS0099: LOG: Probing location 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Linq\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Runtime.dll' because this directory was explicitly added to the search path [File Not Found].
1>POSTSHARP : postsharp error PS0099: LOG: Probing location 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Linq\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Runtime.winmd' because this directory was explicitly added to the search path [File Not Found].
1>POSTSHARP : postsharp error PS0099: LOG: Probing location 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Runtime.Serialization.Primitives\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Runtime.exe' because this directory was explicitly added to the search path [File Not Found].
1>POSTSHARP : postsharp error PS0099: LOG: Probing location 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Runtime.Serialization.Primitives\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Runtime.dll' because this directory was explicitly added to the search path [File Not Found].
1>POSTSHARP : postsharp error PS0099: LOG: Probing location 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Runtime.Serialization.Primitives\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Runtime.winmd' because this directory was explicitly added to the search path [File Not Found].
1>POSTSHARP : postsharp error PS0099: LOG: Probing location 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Runtime.exe' because this directory was explicitly added to the search path [File Not Found].
1>POSTSHARP : postsharp error PS0099: LOG: Probing location 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Runtime.dll' because this directory was explicitly added to the search path [File Not Found].
1>POSTSHARP : postsharp error PS0099: LOG: Probing location 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Runtime.winmd' because this directory was explicitly added to the search path [File Not Found].
1>POSTSHARP : postsharp error PS0099: LOG: Probing location 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Runtime.Serialization\v4.0_4.0.0.0__b77a5c561934e089\System.Runtime.exe' because this directory was explicitly added to the search path [File Not Found].
1>POSTSHARP : postsharp error PS0099: LOG: Probing location 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Runtime.Serialization\v4.0_4.0.0.0__b77a5c561934e089\System.Runtime.dll' because this directory was explicitly added to the search path [File Not Found].
1>POSTSHARP : postsharp error PS0099: LOG: Probing location 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Runtime.Serialization\v4.0_4.0.0.0__b77a5c561934e089\System.Runtime.winmd' because this directory was explicitly added to the search path [File Not Found].
1>POSTSHARP : postsharp error PS0099: LOG: Probing location 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.Runtime.exe' because this directory was explicitly added to the search path [File Not Found].
1>POSTSHARP : postsharp error PS0099: LOG: Probing location 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.Runtime.dll' because this directory was explicitly added to the search path [File Not Found].
1>POSTSHARP : postsharp error PS0099: LOG: Probing location 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.Runtime.winmd' because this directory was explicitly added to the search path [File Not Found].
1>POSTSHARP : postsharp error PS0099: LOG: Probing location 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Xml\v4.0_4.0.0.0__b77a5c561934e089\System.Runtime.exe' because this directory was explicitly added to the search path [File Not Found].
1>POSTSHARP : postsharp error PS0099: LOG: Probing location 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Xml\v4.0_4.0.0.0__b77a5c561934e089\System.Runtime.dll' because this directory was explicitly added to the search path [File Not Found].
1>POSTSHARP : postsharp error PS0099: LOG: Probing location 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Xml\v4.0_4.0.0.0__b77a5c561934e089\System.Runtime.winmd' because this directory was explicitly added to the search path [File Not Found].
1>POSTSHARP : postsharp error PS0099: LOG: Probing location 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Numerics\v4.0_4.0.0.0__b77a5c561934e089\System.Runtime.exe' because this directory was explicitly added to the search path [File Not Found].
1>POSTSHARP : postsharp error PS0099: LOG: Probing location 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Numerics\v4.0_4.0.0.0__b77a5c561934e089\System.Runtime.dll' because this directory was explicitly added to the search path [File Not Found].
1>POSTSHARP : postsharp error PS0099: LOG: Probing location 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Numerics\v4.0_4.0.0.0__b77a5c561934e089\System.Runtime.winmd' because this directory was explicitly added to the search path [File Not Found].
1>POSTSHARP : postsharp error PS0099: LOG: Probing location 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Security\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Runtime.exe' because this directory was explicitly added to the search path [File Not Found].
1>POSTSHARP : postsharp error PS0099: LOG: Probing location 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Security\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Runtime.dll' because this directory was explicitly added to the search path [File Not Found].
1>POSTSHARP : postsharp error PS0099: LOG: Probing location 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Security\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Runtime.winmd' because this directory was explicitly added to the search path [File Not Found].
1>POSTSHARP : postsharp error PS0099: LOG: Probing location 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.ServiceModel.Internals\v4.0_4.0.0.0__31bf3856ad364e35\System.Runtime.exe' because this directory was explicitly added to the search path [File Not Found].
1>POSTSHARP : postsharp error PS0099: LOG: Probing location 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.ServiceModel.Internals\v4.0_4.0.0.0__31bf3856ad364e35\System.Runtime.dll' because this directory was explicitly added to the search path [File Not Found].
1>POSTSHARP : postsharp error PS0099: LOG: Probing location 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.ServiceModel.Internals\v4.0_4.0.0.0__31bf3856ad364e35\System.Runtime.winmd' because this directory was explicitly added to the search path [File Not Found].
1>POSTSHARP : postsharp error PS0099: LOG: Probing location 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\SMDiagnostics\v4.0_4.0.0.0__b77a5c561934e089\System.Runtime.exe' because this directory was explicitly added to the search path [File Not Found].
1>POSTSHARP : postsharp error PS0099: LOG: Probing location 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\SMDiagnostics\v4.0_4.0.0.0__b77a5c561934e089\System.Runtime.dll' because this directory was explicitly added to the search path [File Not Found].
1>POSTSHARP : postsharp error PS0099: LOG: Probing location 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\SMDiagnostics\v4.0_4.0.0.0__b77a5c561934e089\System.Runtime.winmd' because this directory was explicitly added to the search path [File Not Found].
1>POSTSHARP : postsharp error PS0099: LOG: Probing location 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Configuration\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Runtime.exe' because this directory was explicitly added to the search path [File Not Found].
1>POSTSHARP : postsharp error PS0099: LOG: Probing location 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Configuration\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Runtime.dll' because this directory was explicitly added to the search path [File Not Found].
1>POSTSHARP : postsharp error PS0099: LOG: Probing location 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Configuration\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Runtime.winmd' because this directory was explicitly added to the search path [File Not Found].
1>POSTSHARP : postsharp error PS0099: LOG: Probing location 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Data.SqlXml\v4.0_4.0.0.0__b77a5c561934e089\System.Runtime.exe' because this directory was explicitly added to the search path [File Not Found].
1>POSTSHARP : postsharp error PS0099: LOG: Probing location 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Data.SqlXml\v4.0_4.0.0.0__b77a5c561934e089\System.Runtime.dll' because this directory was explicitly added to the search path [File Not Found].
1>POSTSHARP : postsharp error PS0099: LOG: Probing location 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Data.SqlXml\v4.0_4.0.0.0__b77a5c561934e089\System.Runtime.winmd' because this directory was explicitly added to the search path [File Not Found].
1>POSTSHARP : postsharp error PS0099: LOG: Probing location 'C:\Repository\Projects\CriticalArc\packages\PostSharp.4.3.20\tools\System.Runtime.exe' because this directory was explicitly added to the search path [File Not Found].
1>POSTSHARP : postsharp error PS0099: LOG: Probing location 'C:\Repository\Projects\CriticalArc\packages\PostSharp.4.3.20\tools\System.Runtime.dll' because this directory was explicitly added to the search path [File Not Found].
1>POSTSHARP : postsharp error PS0099: LOG: Probing location 'C:\Repository\Projects\CriticalArc\packages\PostSharp.4.3.20\tools\System.Runtime.winmd' because this directory was explicitly added to the search path [File Not Found].
1>POSTSHARP : postsharp error PS0099: LOG: The assembly 'system.runtime, version=4.0.20.0, culture=neutral, publickeytoken=b03f5f7f11d50a3a' was not found.
1>POSTSHARP : postsharp error PS0099: ===============================================================
1>POSTSHARP : postsharp error PS0099:    at PostSharp.Sdk.CodeModel.Domain.GetAssembly(IAssemblyName assemblyName, BindingOptions bindingOptions, AssemblyLoadContext context)
1>POSTSHARP : postsharp error PS0099:    at PostSharp.Sdk.CodeModel.AssemblyRefDeclaration.GetAssemblyEnvelope(BindingOptions bindingOptions)
1>POSTSHARP : postsharp error PS0099:    at PostSharp.Sdk.CodeModel.TypeRefDeclaration.GetTypeDefinition(BindingOptions bindingOptions)
1>POSTSHARP : postsharp error PS0099:    at PostSharp.Sdk.CodeModel.TypeRefDeclaration.BelongsToClassification(TypeClassifications typeClassification)
1>POSTSHARP : postsharp error PS0099:    at PostSharp.Sdk.CodeModel.TypeDefDeclaration.BelongsToClassification(TypeClassifications typeClassification)
1>POSTSHARP : postsharp error PS0099:    at PostSharp.Sdk.CodeModel.TypeDefDeclaration.get_TypeIdentifier()
1>POSTSHARP : postsharp error PS0099:    at PostSharp.Sdk.CodeModel.CompareExtensions.DefinitionMatchesReference(INamedType definition, INamedType reference, BindingOptions options)
1>POSTSHARP : postsharp error PS0099:    at PostSharp.Sdk.CodeModel.TypeDefDeclaration.^A9yFoe2uB3TC(ITypeSignature _0, BindingOptions _1)
1>POSTSHARP : postsharp error PS0099:    at PostSharp.Sdk.CodeModel.TypeDefDeclaration.Equals(ITypeSignature other)
1>POSTSHARP : postsharp error PS0099:    at PostSharp.Sdk.CodeModel.TypeDefDeclaration.^tSmxl0bB4EWP(ITypeSignature _0, GenericMap _1, ^pFrwtoi5k+N4 _2, GenericConstraintCollector _3, GenericMap& _4)
1>POSTSHARP : postsharp error PS0099:    at PostSharp.Sdk.CodeModel.TypeRefDeclaration.^tSmxl0bB4EWP(ITypeSignature _0, GenericMap _1, ^pFrwtoi5k+N4 _2, GenericConstraintCollector _3, GenericMap& _4)
1>POSTSHARP : postsharp error PS0099:    at PostSharp.Sdk.CodeModel.TypeSignatureExtensions.^I95/9py2(ITypeSignature _0, ITypeSignature _1, GenericMap _2, ^pFrwtoi5k+N4 _3)
1>POSTSHARP : postsharp error PS0099:    at PostSharp.Sdk.CodeModel.TypeSignatureExtensions.GetAssignmentDistance(ITypeSignature derivedType, ITypeSignature baseType)
1>POSTSHARP : postsharp error PS0099:    at PostSharp.Sdk.Extensibility.Tasks.DisableMessagesTask.^fssAJztA(CustomAttributeDeclarationCollection _0, ITypeSignature _1, ITypeSignature _2)
1>POSTSHARP : postsharp error PS0099:    at PostSharp.Sdk.Extensibility.Tasks.DisableMessagesTask.Execute()
1>POSTSHARP : postsharp error PS0099:    at PostSharp.Sdk.Extensibility.Project.ExecutePhase(String phase)
1>POSTSHARP : postsharp error PS0099:    at PostSharp.Sdk.Extensibility.Project.Execute()
1>POSTSHARP : postsharp error PS0099:    at PostSharp.Hosting.PostSharpObject.ExecuteProjects()
1>POSTSHARP : postsharp error PS0099:    at PostSharp.Hosting.PostSharpObject.InvokeProject(ProjectInvocation projectInvocation).
========== Build: 0 succeeded, 1 failed, 2 up-to-date, 0 skipped ==========

The thing that I found odd was that System.Reactive nuget package depends on System.Runtime >= 4.1.0, but if you look at System.Reactive.Linq.dll in Reflector it references 4.0.20. That appears to be where the conflict is, but I'm not sure if this is actually PostSharp doing bad things. (I'll raise the issue with them, too).

**Comment by onovotny** [comment]
The package version and the assembly version may not match exactly. With Rx 3, binding redirects are also likely required. This has been fixed with 4.0 where there is only a single assembly now.
