### ISSUE TITLE
Wrong AssemblyVersion of System.Reactive.Linq in 3.1 for portable

### ISSUE THREAD

**Issue by GibSral** [Reactive-Extensions/Rx.NET#296]
When referencing System.Reactive.Linq in a portable assembly the assemblyVersion is 3.0.1000.0
When referencing System.Reactive.Linq in a ".net 4.6.1" assembly the assemblyVersion is 3.0.3000.0

**Comment by shiftkey** [comment]
Please see the discussion about versioning in #205
