### ISSUE TITLE
Add Rx Design Guidelines to source control

### ISSUE THREAD

**Issue by mattpodwysocki** [Reactive-Extensions/Rx.NET#31]
Copied from https://rx.codeplex.com/workitem/62
(Rx Design Guidelines.pdf attachment not included)

I thought it would be good to add the Rx Design Guidelines document to source control, and maintain it on an ongoing basis. It's proved extremely useful to me on several occasions. 

 Current found on MSDN at: 

http://go.microsoft.com/fwlink/?LinkID=205219 

 And attached.

**Comment by bartdesmet** [comment]
Done; in a future release, we may convert this to wiki pages.
