### ISSUE TITLE
Observable.Window with (skip < count) produces no overlap

### ISSUE THREAD

**Issue by cjstephen** [Reactive-Extensions/Rx.NET#310]
I've previously used this to produce a sliding window (overlapping windows)

e.g. Window(o, 5, 2)  =>
1 2 3 4 5
      3 4 5 6 7 
            5 6 7 8 9

But now it seems to only have the full count on the first. The other windows all have length "skip"
Could be my misapprehension, but this seems to be a change in behaviour if the count, skip overload
can produce overlapping windows

Here's a simple example (FSharp):

```#r "../packages/Endorphin.Core/lib/net452/Endorphin.Core.dll"
#r "../packages/log4net/lib/net45-full/log4net.dll"
#r "System.Core.dll"
#r "System.dll"
#r "System.Numerics.dll"
#r "../packages/System.Reactive.Core/lib/net45/System.Reactive.Core.dll"
#r "../packages/System.Reactive.Interfaces/lib/net45/System.Reactive.Interfaces.dll"
#r "../packages/System.Reactive.Linq/lib/net45/System.Reactive.Linq.dll"
#r "../packages/System.Reactive.PlatformServices/lib/net45/System.Reactive.PlatformServices.dll"
#r "../packages/FSharp.Control.Reactive/lib/net45/FSharp.Control.Reactive.dll"

open FSharp.Control.Reactive
open System.Reactive.Linq

let t = seq { 1 .. 20 } |> Observable.ofSeq
 
Observable.Window( t, 5, 2)
|> Observable.map Observable.toArray
|> Observable.concatInner
|> Observable.map (Array.map (sprintf "%d") >> Array.toSeq >> String.concat ", ")
|> Observable.add (printfn "%s")
```

I get the output:

1, 2, 3, 4, 5
6, 7
8, 9
10, 11
12, 13
14, 15
16, 17
18, 19
20

I'm using System.Reactive 3.1.1 on .NET 4.5

**Comment by shiftkey** [comment]
I ported this to C# to try and create a simpler repro:

```csharp
class Program
{
    static void Main(string[] args)
    {
        var range = Observable.Range(1, 20);
        var window = Observable.Window(range, 5, 2);
        window.Subscribe(items =>
        {
            items.ToArray().Subscribe(Output);
        });

        Console.ReadLine();
    }

    static void Output(int[] array)
    {
        Console.Write("[");
        for (var i = 0; i < array.Length; i++)
        {
            Console.Write(" " + array[i]);
        }
        Console.Write(" ]");
        Console.WriteLine();
    }
}
```

This seems to be working as expected:

```
[ 1 2 3 4 5 ]
[ 3 4 5 6 7 ]
[ 5 6 7 8 9 ]
[ 7 8 9 10 11 ]
[ 9 10 11 12 13 ]
[ 11 12 13 14 15 ]
[ 13 14 15 16 17 ]
[ 15 16 17 18 19 ]
[ 17 18 19 20 ]
[ 19 20 ]
[ ]
```

I also kludged together a different version which also works like the C# version:

```fsharp
let formatWindow(observable: IObservable<int[]>): unit = 
    observable
    |> Observable.map (Array.map (sprintf "%d") >> Array.toSeq >> String.concat ", ")
    |> Observable.add (printfn "[ %s ]")
 
Observable.Window(t, 5, 2)
|> Observable.map Observable.toArray
|> Observable.add formatWindow
```

Looking at your sample, the only conceptual difference is with how `concatInner` might be working. I'm avoiding that explicitly, but that also just [wraps](https://github.com/fsprojects/FSharp.Control.Reactive/blob/master/src/FSharp.Control.Reactive/Observable.fs#L366-L367) `Observable.Concat(sources)`, so I'm not sure that's the issue here.

> Could be my misapprehension, but this seems to be a change in behaviour if the count, skip overload can produce overlapping windows

Do you have a version of this (including `FSharp.Control.Reactive`) that worked previously?

**Comment by cjstephen** [comment]
Ah, I see the problem. You're quite right about the concatInner being the difference.
I found the earlier example I was thinking of and it turned out I'd used mergeInner

What's happening appears to be that concatInner only subscribes to the inner observables
on completion of the preceding observable, which is understandable. But they run concurrently,
so merge is appropriate. My test case was at fault!

Sorry to cause you work unnecessarily, I should have spotted that.
Thanks for taking a look
