### ISSUE TITLE
Rx.Net: Add Silverlight 5 support for portable library

### ISSUE THREAD

**Issue by mattpodwysocki** [Reactive-Extensions/Rx.NET#32]
Copied from https://rx.codeplex.com/workitem/34

Silverlight 5 should support all (or almost all) of the portable library API, please add it to the list of supported platforms for the portable library. 

 By not supporting Silverlight 5 you prevent everyone else from building portable libraries compatible with SL5 from using Rx. If you wan't async support just utilize the microsoft.bcl.async package since it add async support

**Comment by rozele** [comment]
This issue has already been resolved as of 2.2.5.  This package was shipped with a build targeted to portable-net40+sl5+win8+wp8.
