### ISSUE TITLE
CompositeDisposable to implement IDisposable

### ISSUE THREAD

**Issue by tugberkugurlu** [Reactive-Extensions/Rx.NET#328]
It seems like [`CompositeDisposable`](https://github.com/Reactive-Extensions/Rx.NET/blob/072abb25ea23e47a49ccae7f1c3a1e4ec4a379e5/Rx.NET/Source/System.Reactive.Core/Reactive/Disposables/CompositeDisposable.cs) doesn't implement `IDisposable`. Any particular reason why since it's very convenient to do so?

**Comment by onovotny** [comment]
`ICancelable` does derive from `IDisposable`
https://github.com/Reactive-Extensions/Rx.NET/blob/371c83c621562a2259580a03f0cb5bf8680ea720/Rx.NET/Source/System.Reactive.Interfaces/Reactive/Disposables/ICancelable.cs#L10
