### ISSUE TITLE
Buffer extension method may not work correctly with Scheduler when Timespan and interval specified.

### ISSUE THREAD

**Issue by mattpodwysocki** [Reactive-Extensions/Rx.NET#33]
Copied from https://rx.codeplex.com/workitem/71

I seem to have found a potential issue with the `Buffer` extension method. 

 I would like to Buffer items coming in on a subject but trigger the Processing of those items either when a batch size is reached, or if a time interval expires. I also need the items to be processed on an individual thread so I am using the `NewThreadScheduler()`. 

 I have written a simple class to demonstrate the issue.
```c#
public class Processor<T>
{
    private readonly HashSet<int> _threadIds = new HashSet<int>();
    private readonly Subject<T> _queue;
    private readonly IDisposable _observation;

    private int _count;

    public Processor(TimeSpan interval, int batchSize)
    {
        _queue = new Subject<T>();
        var scheduler = new NewThreadScheduler();
        _observation = _queue.Buffer(interval, batchSize, scheduler).Subscribe(Process);
    }

    public IEnumerable<int> ProcessThreadIds
    {
        get
        {
            return _threadIds;
        }
    }

    public int Count
    {
        get
        {
            return _count;
        }
        set
        {
            _count = value;
        }
    }

    public void Stop()
    {
        _observation.Dispose();
    }

    public void Add(T item)
    {
        _queue.OnNext(item);
    }

    private void Process(IList<T> item)
    {
        _threadIds.Add(Thread.CurrentThread.ManagedThreadId);
        Count += item.Count;
    }
}
```
I have run this using the following code:
```c#
public static void Main(string[] args)
{
    Console.WriteLine("Main Thread Id: {0}", Thread.CurrentThread.ManagedThreadId);
            
    var processor = new Processor<int>(new TimeSpan(0, 0,0, 0, 500), 100);

    var tasks = new List<Task>();

    var random = new Random(7);

    for (int i = 0; i < 10; i++)
    {
        var task = new Task(
            () =>
                {
                    for (int j = 0; j < 1000; j++)
                    {
                        processor.Add(j);

                        Thread.Sleep(random.Next(5, 10));
                    }
                });

        tasks.Add(task);
        task.Start();
    }

    Task.WaitAll(tasks.ToArray());

    while (processor.Count < 10000)
    {
        Thread.Sleep(100);
    }

    Console.WriteLine("Recorded the following Process thread ids: {0}", string.Join(",", processor.ProcessThreadIds.Distinct()));

    processor.Stop();
    Console.ReadKey();
}
```
I would have expect that _threadIds only ever contains 1 thread id. This is the case if I provide just an interval or just a batch size ... but if I include both, then _threadIds contains multiple thread ids. 

 Interestingly if I use `ObserveOn` to provide the same scheduler, I still see the same issue (this may actually be more likely to be an issue).
`_queue.ObserveOn(scheduler).Buffer(interval, batchSize).Subscribe(Process);`
Can anyone explain what is happening? And if it is by design, how I may be able to achieve what I need? 

 Thanks 

 David

**Comment by bartdesmet** [comment]
This is by design. The NewThreadScheduler is allowed to create new threads for individual scheduling operations. EventLoopScheduler does what you want in this case.

For what the discrepancy between interval/count and interval based Buffer is concerned, in the latter case we can use "periodic scheduling" on the NewThreadScheduler which runs a loop on the thread with sleeps in between action invocations, hence causing the same thread to be used, as an optimization.

This is not in conflict with the NewThreadScheduler design which allows for new threads to be allocated for each individual action. Notice NewThreadScheduler uses an EventLoopScheduler construct internally with an "ExitIfEmpty" flag set, meaning threads can quit if they don't have work left to do.
