### ISSUE TITLE
Join emits pairs twice

### ISSUE THREAD

**Issue by mattpodwysocki** [Reactive-Extensions/Rx.NET#35]
Copied from https://rx.codeplex.com/workitem/68

This has come up in RxJava development: ReactiveX/RxJava#831

Basically, when left and right emit their values in a way that, for example, the right's emission falls between L112 - L129 of Join.cs, both parties will emit left and right values. Is this expected or a bug?

**Comment by bartdesmet** [comment]
This has been fixed for the next Rx.NET release.
