### ISSUE TITLE
EventLoopScheduler throw random NullReferenceException

### ISSUE THREAD

**Issue by mattpodwysocki** [Reactive-Extensions/Rx.NET#40]
Copied from https://rx.codeplex.com/workitem/7

We use Windows 7 with 64 bit in a production computer. in RX1.1.11111.1 all was fine. when we migrated to RX 2.0.20823.2 we have encountered a random exception from the `EventLoopScheduler`: 
```
 an Unhandled Exception occured in non UI thread. 
 System.NullReferenceException: Object reference not set to an instance of an object. 
 at System.Reactive.Concurrency.EventLoopScheduler.Run() 
 at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean ignoreSyncCtx) 
 at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state) 
 at System.Threading.ThreadHelper.ThreadStart() 
```

 Here's the gist of the code: 
```c#
 EventLoopScheduler m_scheduler = new EventLoopScheduler(); 

 . . . 

 m_receivedMessageHandler.StatusReceived.ObserveOn(m_scheduler) .Subscribe(p_unit => sendAll(m_retransmitManager, m_endPoint)); 
```
 We have seen an answer to [our post](http://social.msdn.microsoft.com/Forums/mr/rx/thread/74a59f34-50ef-4c8a-a492-e63ff5eafe26) which indicated it is a JIT problem in 64 bit.

**Comment by bartdesmet** [comment]
Unfortunately, we've been unable to repro this issue thus far. I'll keep the issue open for a bit longer in case someone can post a link to a crash dump, which could help the investigation.

**Comment by bartdesmet** [comment]
Some stress tests on various versions of the CLR in 64 bit haven't revealed this issue thus far. Closing the issue for now. If you got more information, please reopen.
