### ISSUE TITLE
.NET 4.0

### ISSUE THREAD

**Issue by ktodyruik-ipl** [Reactive-Extensions/Rx.NET#403]
Hi,

What was the last version of Rx.NET that targeted .NET 4.0? And where can I get it from?

Thanks,
Kerry

**Comment by shiftkey** [comment]
I think `2.2.5` is the latest version, and you'll have to install it manually through NuGet:

```
Install-Package Rx-Main -Version 2.2.5
```

**Comment by ktodyruik-ipl** [comment]
@shiftkey Thanks!
