### ISSUE TITLE
Using System.Reactive and Rx-... packages in one project causes compiler errors

### ISSUE THREAD

**Issue by roy-t** [Reactive-Extensions/Rx.NET#416]
It recently came to my attention that the Rx-... nuget packages have been renamed System.Reactive. This causes problems when other NuGet packages bring both the old and the new packages.

**Reproduction**
- Install ReactiveUI (this will bring in Rx-Main and others)
- install WpfTabTip (this will bring in System.Reactive)

**Write the following code**

`ReactiveCommand.Create(() => { });`

**You will get the following error messages:**

`error CS0012: The type 'Unit' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Reactive.Core, Version=2.2.5.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.`

`error CS0012: The type 'IScheduler' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Reactive.Interfaces, Version=2.2.5.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.`

Normally having a higher version of the System.Reactive/Rx package wouldn't be a problem for packages that depend on it. But I think the name change messes things up. The only fix that we currently have is to download the full source code of WpfTabTip, include it in our product and then make it use the Rx-... packages. (It doesn't use any new functionality) But of course this is 100% against the spirit  of having a packaging system.

Is there a mechanism in NuGet that should tell us that the package is renamed, that is not working, or is there some assembly redirect or another trick that we can use to fix this?

**Comment by onovotny** [comment]
Hi @roy-t, unfortunately we had to change the strong name key as part of moving to the .NET Foundation. The older strong-name key was a Microsoft key, so we'd never be able to check that in. It's  not just a matter of packages, binding redirects would not work either since the public key wouldn't match.

For RxUI, I know they're planning on moving to Rx 3.x soon. /cc @ghuntley

**Comment by roy-t** [comment]
Ah that's unfortunate. I hope the newest version of ReactiveUI is released soon (and doesn't completely change commands again ;) ). Nothing we can do for now. I think its OK to close this issue.

**Comment by ghuntley** [comment]
@roy-t no changes to RxCommands :)

Head on over to reactiveui.net/slack btw.
