### ISSUE TITLE
Split Ix test projects

### ISSUE THREAD

**Issue by bartdesmet** [Reactive-Extensions/Rx.NET#422]
We should have one test project for `System.Interactive` and another one for `System.Interactive.Async`.

**Comment by mattpodwysocki** [comment]
@onovotny @bartdesmet we should go further to split each method under test in async to its own file.

**Comment by onovotny** [comment]
Nevermind it's own file, but each should have its own test class. You'll get far better perf in xunit that way. xunit will parallelize tests across test classes but within each test class, only one executes at a time.
