### ISSUE TITLE
Add message to Timeout operator

### ISSUE THREAD

**Issue by mattpodwysocki** [Reactive-Extensions/Rx.NET#47]
Copied from https://rx.codeplex.com/workitem/42

Request to have the Timeout operators to accept an additional message parameter. This would be added as the TimeoutException message e.g. new TimeoutException(message).

**Comment by bartdesmet** [comment]
Thanks for the suggestion, but we won't be adding those overloads. It's a slippery slope to add overloads that inherit constructors from TimeoutException; for completeness, we'd have to add an overload with an inner exception parameter as well. The generalization likely would be an overload that takes in a Func<TimeoutException> to construct exception objects on the fly. However, existing overloads for Timeout already provide this functionality, namely via the "IObservable<TSource> other" parameter. One can put in a Throw<TSource> there to specify the exception object, or even wrap it with a Defer<TSource> operator to create new exception objects each time. We feel this provides the flexibility needed through composition.
