### ISSUE TITLE
AsyncEnumerable.SelectMany must dispose inner IAsyncEnumerators

### ISSUE THREAD

**Issue by danielcweber** [Reactive-Extensions/Rx.NET#5]
Hi,

raised this on CodePlex too some months ago, to no avail.

Before
https://github.com/Reactive-Extensions/Rx.NET/blob/a2a03840ac8417fec14e53cfc31adfd7fef1635f/Ix.NET/Source/System.Interactive.Async/AsyncEnumerable.Single.cs#L268
it is crucial that the inner enumerator instance is disposed. We've run into leaks repeatedly. The inner enumerator also leaks whenever the outer is disposed and the inner has not completed.

Thanks
Daniel

**Comment by bartdesmet** [comment]
This has been checked in a while ago. We'll review the other changes proposed by danielcweber.
