### ISSUE TITLE
TypeLoadException when using Yielder

### ISSUE THREAD

**Issue by mattpodwysocki** [Reactive-Extensions/Rx.NET#52]
Copied from https://rx.codeplex.com/workitem/20

With Ix-Main 0.9.0.2 from the NuGet package, trying to use Yielder as in this example ( https://gist.github.com/mausch/5241729 ) throws a `TypeLoadException`:
```c#
Unhandled Exception: System.TypeLoadException: Inheritance security rules violated while overriding member: 'System.Linq.Yielder`1<T>.UnsafeOnCompleted(System.Action)'. Security accessibility of the overriding method must match the security accessibility of the method being overriden.
   at System.Linq.EnumerableEx.<Create>d__a6`1.MoveNext()
   at System.Linq.Enumerable.ElementAt[TSource](IEnumerable`1 source, Int32 index)
   at ConsoleApplication21.Program.Main(String[] args) in g:\prg\ConsoleApplication21\ConsoleApplication21\Program.cs:line 15
```

Earlier I copied the code from this diff (  http://rx.codeplex.com/SourceControl/changeset/8f1e73bca96e ) instead of using the NuGet package and the same example worked fine.

**Comment by bartdesmet** [comment]
UnsafeOnCompleted was marked with SecurityCriticalAttribute a while ago. This should have addressed this issue.
