### ISSUE TITLE
ConnectableObservable Factory

### ISSUE THREAD

**Issue by mattpodwysocki** [Reactive-Extensions/Rx.NET#54]
Copied from https://rx.codeplex.com/workitem/16

Consider creating factory methods that return `IConnectableObservable<T>` similar to the `Create` factory methods that return `IObservable<T>`.

Related discussion and example code:
http://social.msdn.microsoft.com/Forums/en-US/rx/thread/4b89144c-045f-4497-919c-24fb6e1d1215/

**Comment by bartdesmet** [comment]
Per the discussion on the forum, there's a better solution that doesn't involve IConnectableObservable<T> at all. We'd rather not stimulate the use of connectables beyond the sharing of side-effects through multicast operators, so - at this point - the introduction of factory methods for IConnectableObservable<T> is off the table.
