### ISSUE TITLE
Add MS Code Contract assemblies to NuGet packages?

### ISSUE THREAD

**Issue by mattpodwysocki** [Reactive-Extensions/Rx.NET#56]
Copied from https://rx.codeplex.com/workitem/14

Right now I am taking the RX Contract Assemblies Dave has made over in the RXX project and manually creating new NuGet packages to put in my company NuGet repo so we can get code contracts working with Rx. I'll have to do this everytime I upgrade versions of RX.

Is there any chance you can start including contract assemblies in the NuGet releases?

**Comment by shiftkey** [comment]
@mattpodwysocki is this something that we still care about?

**Comment by mattpodwysocki** [comment]
@shiftkey nope!
