### ISSUE TITLE
Catch<T> doesn't catch exceptions from Defer

### ISSUE THREAD

**Issue by niik** [Reactive-Extensions/Rx.NET#61]
I recently noticed a rather surprising inconsistency between ```Catch<TSource>``` and ```Catch<TSource,TException>```. Take this example

```cs
Observable.Defer<string>(() => {
    throw new InvalidOperationException("Foo");
    return Observable.Return("Success");
})
.Catch(Observable.Return("Failed the first time"))
.Catch<string, Exception>(ex => Observable.Return("Failed the second time"))
.Do(Console.WriteLine)
.Wait();
```

I would expect that to output "Failed the first time" but what actually happens is that the exception from the Defer falls through the first Catch and is caught by the second, thus writing "Failed the second time".

If I change the ```Defer``` to a ```Throw```...
```cs
Observable.Throw<string>(new InvalidOperationException("Foo"))
    .Catch(Observable.Return("Failed the first time"))
    .Catch<string, Exception>(ex => Observable.Return("Failed the second time"))
    .Do(Console.WriteLine)
    .Wait();
```
...everything works as expected and it outputs "Failed the first time".

I believe this is caused by [TailRecursiveSink.MoveNext](https://github.com/Reactive-Extensions/Rx.NET/blob/v2.2.5/Rx.NET/Source/System.Reactive.Linq/Reactive/Internal/TailRecursiveSink.cs#L97) trying to optimize the execution by unpacking the deferred and running the factory immediately. When the exception from that factory is caught it [is delivered to the subscriber](https://github.com/Reactive-Extensions/Rx.NET/blob/v2.2.5/Rx.NET/Source/System.Reactive.Linq/Reactive/Internal/TailRecursiveSink.cs#L102) (in this case the second Catch). I believe this is wrong and it should instead marshal the exception to the [Catch sink](https://github.com/Reactive-Extensions/Rx.NET/blob/v2.2.5/Rx.NET/Source/System.Reactive.Linq/Reactive/Linq/Observable/Catch.cs#L27).

I am a bit concerned with the [Done method](https://github.com/Reactive-Extensions/Rx.NET/blob/v2.2.5/Rx.NET/Source/System.Reactive.Linq/Reactive/Linq/Observable/Catch.cs#L62-L70) in the Catch sink though. It looks to me like it will publish the exception when the parent sink completes but I haven't dug further into that.

Contrast this with what the ```Catch<TSource,Exception>``` [sink does](https://github.com/Reactive-Extensions/Rx.NET/blob/v2.2.5/Rx.NET/Source/System.Reactive.Linq/Reactive/Linq/Observable/Catch.cs#L123-L135). The only time it will publish an exception to its subscriber is when the handler itself throws.

I verified this on 2.2.0 and 2.2.5.

**Comment by bartdesmet** [comment]
This is the right place indeed. We're looking into this for a future Rx release.

**Comment by bartdesmet** [comment]
This is fixed for the upcoming Rx .NET release.

**Comment by niik** [comment]
For people watching at home I believe https://github.com/Reactive-Extensions/Rx.NET/commit/ff932c0af4f7c2b68cc32483b499ffeb8e8599c1 is the gist of the fix

Right @bartdesmet ?
