### ISSUE TITLE
DoAsync Operator Similar to the Async Overloads of SelectMany

### ISSUE THREAD

**Issue by RxDave** [Reactive-Extensions/Rx.NET#63]
It wouldn't enable any new scenarios. It's just about the semantics.

Example: 
http://stackoverflow.com/questions/26716527/cancel-rx-net-observers-ongoing-onnext-methods/26727853#26727853

**Comment by bartdesmet** [comment]
This is some area we'll consider when introducing async Rx constructs, based on what we built for distributed event processing in Bing. Closing this item for now, given it doesn't apply to the current Rx, where we'll keep async signatures in conversions only.

As @bman654 points out, there's quite some use for `SubscribeAsync` and various async operators. Stay tuned for more on that in the not-so-distant future.
