### ISSUE TITLE
AspNetCore50/Core50 build?

### ISSUE THREAD

**Issue by avanderhoorn** [Reactive-Extensions/Rx.NET#64]
Just wondering if there has been any talk or progress made yet on having a build targeting AspNet50/Core50 yet?

**Comment by bartdesmet** [comment]
Please let us know the build targets you care about for future releases as we're planning for it now. In fact, we just shipped an update for Ix to deal with some platform targets in the portable library build, and we'll continue to provide updates to make sure you can run our binaries where needed (provided the targets are recent and/or forward-looking platforms). Thanks!

**Comment by onovotny** [comment]
@bartdesmet Added item for Xamarin.iOS Unified (64-bit) support at #76

**Comment by CoreyKaylor** [comment]
Agreed, dnxcore50 would be nice. It currently seems to work out okay with the current lib references with the exception of the TestScheduler. For now I've brought in the parts I need into my test project with the hopes after a release compatible for dnxcore50 is out.

**Comment by pvasek** [comment]
+1 for dnxcore50

**Comment by Hobb** [comment]
+1 here too

**Comment by BlasVilla** [comment]
+1 for dnxcore50. Could you provide a workaround for the time being?

**Comment by onovotny** [comment]
Done/tracked in #148

**Comment by onovotny** [comment]
Completed, shipping on 6/27!
