### ISSUE TITLE
Assembly version discrepancy between NuGet and GitHub/CodePlex repository

### ISSUE THREAD

**Issue by davidwin** [Reactive-Extensions/Rx.NET#66]
The current NuGet version of Rx.NET is v2.2.5, which is also the assembly version of all binaries. The latest commit in the GitHub repository is labelled 2.2.5, but the source files specify assembly version 2.2.0.

Is the source code that is hosted on GitHub the one that is used for building the NuGet releases? The CodePlex repository seems even more out of date, so I assume that it is abandoned.

**Comment by rozele** [comment]
In terms of updating the assembly version number, we could do this, but it would be for cosmetic purposes only.  The NuGet packages are strong name signed prior to being shipped, so no matter what any binaries compiled from source are going to be incompatible with those shipped in NuGet.  For now, we'll leave the AssemblyInfo.cs as is.  When we ship the next major version of Rx, we'll likely update the AssemblyInfo.cs then, at which point the AssemblyVersion attribute will no longer be incremented for minor and patch version updates of NuGet packages.
