### ISSUE TITLE
AsyncEnumerable locks up

### ISSUE THREAD

**Issue by Porges** [Reactive-Extensions/Rx.NET#72]
This is the same issue as originally reported here: https://social.msdn.microsoft.com/Forums/en-US/f1b0ca02-675f-4dd7-9519-9670b6b2594a/bug-in-asyncenumerable-or-asyncctp?forum=rx

This doesn't appear to be fixed in the current version of Ix (or has reappeared).

The code in the original, adjusted for the newer terminology, is (I also adjusted to NUnit attributes):

    using System;
    using System.Collections.Generic;
    using System.Diagnostics;
    using System.Linq;
    using System.Reactive.Concurrency;
    using System.Reactive.Linq;
    using System.Threading;
    using System.Threading.Tasks;
    using NUnit.Framework;

    namespace AsyncAwaitBugTest
    {
        [TestFixture]
        public class AsyncAwaitBugTests
        {
            [Test]
            public void TestPushPopAsync()
            {
                var stack = new Stack<int>();
                var count = 10;

                var observable = Observable.Generate(
                  0,
                  i => i < count,
                  i => i + 1,
                  i => i,
                  i => TimeSpan.FromMilliseconds(1), // change this to 0 to avoid the problem [1]
                  Scheduler.Default);

                var task = DoSomethingAsync(observable, stack);

                // we give it a timeout so the test can fail instead of hang
                task.Wait(TimeSpan.FromSeconds(2));

                Assert.AreEqual(10, stack.Count);
            }

            private async Task DoSomethingAsync(IObservable<int> observable, Stack<int> stack)
            {
                var ae = observable
                  .ToAsyncEnumerable()
                  //  .Do(i => { })   // or here [2]
                  .GetEnumerator();

                while (await ae.MoveNext())
                {
                    var i = ae.Current;
                    Debug.WriteLine("Doing something with " + i);
                    Thread.Sleep(50);
                    stack.Push(i);
                }
            }
        }
    }

This fails with 1.2.2 and with 1.2.3-beta.

**Comment by bartdesmet** [comment]
This issue has been fixed now and will appear in the next release of Ix-Async.
