### ISSUE TITLE
Performance implementations of Disposables

### ISSUE THREAD

**Issue by LeeCampbell** [Reactive-Extensions/Rx.NET#75]
As the disposable primitives are part of the building blocks of Rx, it seem pertinent to consider optimizing their performance. There two key question marks I have with the current (v2) implementations of the Disposable implementations:

 1. It has come to my attention that there is the interface `ICancelable` which extends `IDisposable` by adding the `bool IsDisposed {get;}` property. I don't believe this is feature is widely known about and therefore is not widely used.
 2. The use of locks is prevalent in some of the implementations of the Disposables.

While neither of these two things are sinister in themselves, I believe that 3 of the implementations could improve if they were to make a breaking change and stop implementing `ICancelable`. For some implementations, this is virtually free to implement, so I see no harm. However if for example `SerialDisposable` did not implement `ICancelable` and did not expose an `IsDisposed` there would be no need for the internal locking; it could be upgraded to a lock free design.

## Microtesting
As a rudimentary test, I put together a console app and tested to the existing `SerialDisposable` implementation versus what I believe to be a correct lock-free implementation. The test was simply how fast could I loop through and array of 10Million IDisposable instances and assign them to the `SerialDisposable`. The test results were measured after 3 dummy runs for each implementation, with the intention of removing any JIT variations. The gains seemed to be around 90% increase. Not quite earth shattering, but I thought worth pointing out.

## Proposal
If the Rx.NET team are happy to make breaking changes in v3, then I would like to submit for consideration the optimization of the following three types:

### SerialDisposable
Clone the existing implementation into another type (`SerialCancelable`?), and then re-implement the original type as a lock-free. This also has the tiny benefit of not allocating the extra gate object per instance.

### MultipleAssignmentDisposable
As per the `SerialDisposable` - make a clone version with existing features, and then re-implement as lock-free.

### CompositeDisposable
From what I have seen in the wild, the most common case for using the `CompositeDisposable` is to simply construct an instance with the child resources, and never modify it. Usually it is just returned from a method eg:

    var d = new CompositeDisposable(2) { state.sink, state.subscription };

or

    return new CompositeDisposable(state.sink, state.subscription);

I believe there is room for improvement on several fronts here.
 * Drop the implementation of `ICollection<IDisposable>`
 * Drop the implementation of `ICancelable`
 * Make immutable. This obviates the need for locking
As per above there would need to be an implementation that support the current features (`DisposableCollection`?). There could be a small memory requirement improvement by minimizing the implementation i.e. it now would need only a backing array (instead of the flag, counter, gate and list it currently has).

**Comment by bartdesmet** [comment]
We're looking into the vNext design right now. The Rx-based large scale event processing infrastructure we built in Bing did away with the original disposables design, so this item may be superseded depending on how we decide to proceed with compatibility in mind. Stay tuned for this.

**Comment by bartdesmet** [comment]
As part of an upcoming minor Rx.NET release, we've implemented an optimization around CompositeDisposable which is most often used. This mainly helps with memory and also addresses some of the locking concerns above. Future releases of Rx.NET may change the disposable management in a different way, so we'll close this for now given the new optimizations that have been checked in for the Rx v2.x product family.
