### ISSUE TITLE
Xamarin.iOS Unified support

### ISSUE THREAD

**Issue by onovotny** [Reactive-Extensions/Rx.NET#76]
This should be identical to the MonoTouch projects but they link against a different set of core libraries and should go into the lib\Xamarin.iOS NuGet folder.

**Comment by rozele** [comment]
Rx 2.3 will be shipped in the coming weeks, at which point one of the builds will be targeted to portable-net45+netcore45+wpa81+wp8+MonoAndroid1+MonoTouch1, which should support Xamarin.iOS.
