### ISSUE TITLE
Signature of Using complicates usage and involves unnecessary coupling

### ISSUE THREAD

**Issue by davidmoten** [Reactive-Extensions/Rx.NET#77]
https://github.com/Reactive-Extensions/Rx.NET/blob/d50374813e99489eba181d1eeed2084c5da077a9/Rx.NET/Source/System.Reactive.Linq/Reactive/Linq/Observable/Using.cs

I contribute to RxJava where the signature for the Using operator was copied from ReactiveExtensions. I suggested an improvement to the signature for Using that was accepted and it struck me that I should contribute the improvement back to the source being ReactiveExtensions. 

Discussion is at  https://github.com/ReactiveX/RxJava/issues/1466

**Comment by davidmoten** [comment]
I think you may have closed the wrong issue with this commit.

**Comment by bartdesmet** [comment]
The design in Rx.NET is based on the fact that subscriptions are represented using `IDisposable` which is also used by the `using` keyword in languages like C#, which is where the `Using` operator borrows its name from. As such, one doesn't have to do anything special to implement `IDisposable` for existing resources such as I/O streams etc.

This differs from RxJava where the resource has to implement the `Subscription` interface, hence the blind porting of .NET's `Using` operator makes it look strange and introduces coupling. The closest would have been to make subscriptions use `Closeable` in Java, and have an operator called `TryWithResources` in lieu of `Using`, further constraining the resource to deriving from `AutoCloseable`.
