### ISSUE TITLE
Rx.Net ToTask throws TaskCanceledException missing CancellationToken

### ISSUE THREAD

**Issue by Lukazoid** [Reactive-Extensions/Rx.NET#78]
Copied from https://rx.codeplex.com/workitem/85

The method `ToTask<TResult>(this IObservable<TResult> observable, CancellationToken cancellationToken, object state)` in [TaskObservableExtensions](https://github.com/Reactive-Extensions/Rx.NET/blob/a2a03840ac8417fec14e53cfc31adfd7fef1635f/Rx.NET/Source/System.Reactive.Linq/Reactive/Threading/Tasks/TaskObservableExtensions.cs#L195) calls `tcs.TrySetCanceled` without passing the `CancellationToken`.

This can result in a `TaskCanceledException` being thrown with an incorrect value for [TaskCanceledException.CancellationToken](https://msdn.microsoft.com/en-us/library/system.operationcanceledexception.cancellationtoken(v=vs.110).aspx).

I believe the fix is as simple as calling `tcs.TrySetCanceled(cancellationToken)`.

**Update**
Despite appearing in the MSDN as of 4.5 [here](https://msdn.microsoft.com/en-us/library/dn765345(v=vs.110).aspx), it appears `TrySetCanceled(cancellationToken)` does not currently exist and may only appear in 4.6.

**Comment by bartdesmet** [comment]
This has been added for the next release using an enlightenment service that will light up this functionality on .NET 4.6 only.
