### ISSUE TITLE
Operator Join/TestScheduler same-time scheduling order

### ISSUE THREAD

**Issue by akarnokd** [Reactive-Extensions/Rx.NET#79]
Hello, I'm trying to understand TestScheduler. Given two tasks scheduled to the exact same time, do these tasks execute in FIFO order? In ```JoinOp_Normal_I```, I'd expect ```6man``` to appear before ```7man``` (RxJava behaves like this). If it is FIFO, then is it possible the right source emission of "man" emits the left's open values (6, 7) in opposite order because dictionary traversal is different?

**Comment by bartdesmet** [comment]
Yes, we do have FIFO order. In this case, the order of the events is due to the dependency on traversal order of the dictionary. We'll take a closer look at it and consider whether this warrants a change.

**Comment by bartdesmet** [comment]
This has been fixed for the next version of Rx.NET.
