### ISSUE TITLE
Consider relaxing CheckDisposed in BehaviorSubject

### ISSUE THREAD

**Issue by slorion** [Reactive-Extensions/Rx.NET#80]
`BehaviorSubject<T>` will throw an `ObjectDisposedException` when getting the `Value` property and there is no way to check that the subject has been disposed. This is causing us some headaches because we have to deal with various timing issues where we might be getting the value just a bit too late. Would it be possible to relax this constraint or at least provide a way to know that the subject has been disposed ?

**Comment by bartdesmet** [comment]
We'll take a look into this, though retaining the value after disposal is in conflict with the dispose logic. We could add an `IsDisposed` property, though it's obviously not reliable when a concurrent call to `Dispose` is made. Who controls disposing the subject in your case?

**Comment by slorion** [comment]
We made a multiagent system and an agent will get disposed along with its observables by the agent manager. Agents may be on remote machines and be subscribed via a TCP Qbservable provider. Before other agents are notified that a particular agent has been disposed, their subscription to the disposed agent will still be active. We may also expose the current state of the observable via a property delegating to `BehaviorSubject<T>.Value` (which is the specific use case that was hard to manage for us without dealing with `ObjectDisposedException`).

**Comment by bartdesmet** [comment]
Maybe we could add a TryGetValue method that combines an IDisposed check and obtaining the latest value, if any.

**Comment by bartdesmet** [comment]
We made some enhancements to subjects including an `IsDisposed` property and a `TryGetValue` method on `BehaviorSubject<T>`. For a future release, we may consider more inspection capabilities for subjects, e.g. the notification history of a `ReplaySubject<T>`.

**Comment by slorion** [comment]
Great! I will take a look. Thank you!
