### ISSUE TITLE
ToLookup doesn't match Enumerable.ToLookup behaviour

### ISSUE THREAD

**Issue by Lukazoid** [Reactive-Extensions/Rx.NET#82]
When using [`Enumerable.ToLookup`](https://msdn.microsoft.com/en-us/library/vstudio/system.linq.enumerable.tolookup(v=vs.100).aspx), if a key does not exist in the resulting `ILookup<,>` an empty sequence is returned. In the Rx.NET implementation, a `KeyNotFoundException` is thrown instead, this seems to violate the contract of the [`ILookup<TKey, TElement>.Item`](https://msdn.microsoft.com/en-us/library/vstudio/bb549314(v=vs.100).aspx) property which does not specify any thrown exceptions.

The fault can be seen in [Lookup.cs](https://github.com/Reactive-Extensions/Rx.NET/blob/fcf00a1d0c95672934609b6a2dbb4b93fca55428/Rx.NET/Source/System.Reactive.Linq/Reactive/Internal/Lookup.cs#L38). I believe this should be using `TryGetValue` and returning `Enumerable.Empty` if the key is not found.

**Comment by bartdesmet** [comment]
Fixed.
