### ISSUE TITLE
Ix.Async: Take(1) from SelectMany() throws NullReferenceException

### ISSUE THREAD

**Issue by danielcweber** [Reactive-Extensions/Rx.NET#86]
The latest release of Ix.Async has two changes:
1. `Take` disposes the inner `IAsyncEnumerator` early (009b14de43bbee00cc45a53fec51823a26609031).
2. `SelectMany` disposes the inner `IAsyncEnumerator` after all (d865f9d714b1f2da6c860bf313869c8beeebd25d).

Together, these fixes do not go along well, since `Take` accesses the `Current`-property of its inner enumerator after it has been disposed, but unfortunately due to [this](https://github.com/Reactive-Extensions/Rx.NET/blob/fcf00a1d0c95672934609b6a2dbb4b93fca55428/Ix.NET/Source/System.Interactive.Async/AsyncEnumerable.Single.cs#L260) and [this](https://github.com/Reactive-Extensions/Rx.NET/blob/fcf00a1d0c95672934609b6a2dbb4b93fca55428/Ix.NET/Source/System.Interactive.Async/AsyncEnumerable.Single.cs#L354), it results in a NullReferenceException.

**Comment by bartdesmet** [comment]
This has been fixed for the next release of Ix.NET.
