### ISSUE TITLE
Consider shipping symbol files

### ISSUE THREAD

**Issue by james-world** [Reactive-Extensions/Rx.NET#89]
It would be awesome to include symbol files indexed to the github source in the nuget packages...

**Comment by davidwin** [comment]
I second this! At the moment however it looks like official development has ceased in favor of RxJS, so don't hold your breath.

An alternative is to build from source yourself, but you run into #66, need to disable signature checking etc. if you want a drop-in replacement for the official binaries.

**Comment by aateeque** [comment]
This is much needed!

**Comment by bradphelan** [comment]
+1

**Comment by onovotny** [comment]
Symbol files will be shipped as part of 3.0. #184
