### ISSUE TITLE
Add WithLatestFrom

### ISSUE THREAD

**Issue by khellang** [Reactive-Extensions/Rx.NET#90]
I'd :heart: to see the `withLatestFrom` method from RxJava and RxJS be ported over to .NET as well.

![Marbles](http://reactivex.io/documentation/operators/images/withLatestFrom.png)

For reference: http://rxmarbles.com/#withLatestFrom

**Comment by james-world** [comment]
This is an implementation:

    public static IObservable<TResult> WithLatestFrom<TLeft, TRight, TResult>(
        this IObservable<TLeft> source,
        IObservable<TRight> other,
        Func<TLeft, TRight, TResult> resultSelector)
    {
        return other.Publish(os =>
            source.SkipUntil(os.Take(1))
                  .Zip(os.MostRecent(default(TRight)), resultSelector));
    }

**Comment by khellang** [comment]
I have something like this that's working (I think :stuck_out_tongue:):

```csharp
public static IObservable<TResult> WithLatestFrom<TResult, TFirst, TSecond>(
    this IObservable<TFirst> first,
    IObservable<TSecond> second,
    Func<TFirst, TSecond, TResult> resultSelector)
{
    return Observable.Create<TResult>(observer =>
    {
        var replay = first.Publish();

        var connection = replay.Connect();

        var subscription = second
            .Select(a => replay
                .Select(b => resultSelector(b, a)))
            .Switch()
            .Subscribe(observer);

        return new CompositeDisposable(connection, subscription);
    });
}
```

**Comment by james-world** [comment]
It passes my test, but it's got slightly more code in! ;)

**Comment by danyx23** [comment]
:+1:
This is a pretty useful operator and should come with rx .net by default

**Comment by bartdesmet** [comment]
This operator has been added for the next release of Rx.NET.

**Comment by khellang** [comment]
Thanks, @bartdesmet! :+1:
