### ISSUE TITLE
Clarification on portability of RX.NET?

### ISSUE THREAD

**Issue by axefrog** [Reactive-Extensions/Rx.NET#95]
I'm quite confused as to what the status of Rx.Net is with regards to its portability. Specifically, .Net 5.0 is being targeted at both OSX and Linux, so where does that leave Rx.Net? I see that Rx-Main has a dependency on PlatformServices, which scant information (found via Google) seems to suggest is not particularly portable. I'm experimenting with building a portable game engine using .Net and I'm trying to make decisions that won't negatively impact my ability to port the core components to other platforms. If I take a dependency on Rx-Main now, am I going to be kicking myself a year down the road and having to refactor the whole thing out in favour of some other event streaming library?

**Comment by james-world** [comment]
Rx is portable and usable on Mono - I don't have personal experience with this, but I know that [ReactiveUI](http://reactiveui.net/) which uses Rx runs on the Xamarin platform on iOS and Android.

PlatformServices is an abstraction designed to take advantage of platform specific capabilities where they exist. There's a fairly good explanation of how it works in [this video](http://channel9.msdn.com/Shows/Going+Deep/Bart-De-Smet-Rx-20-RTM-and-RTW) - note that although this is from August 2012, the concept remains unchanged.

**Comment by bartdesmet** [comment]
Correct. The PlatformServices assembly is intentionally not portable and contains all the platform-specific capabilities that can be used to "light up" the portable functionality in Interfaces, Core, Linq, and Providers assemblies. You can safely take a bet on the portability of Rx. Let us know if you run into any issue.

**Comment by axefrog** [comment]
Ok, thanks!
